# LEVELS Benchmark: DSI Data Explorer Agent

This notebook benchmarks the DSI Data Explorer agent across three task-complexity levels and five data-management categories.

## Complexity Levels

| Level | Name | Description | Scoring Method |
|-------|------|-------------|---------|
| **1** | Atomic | Single DSI/API call from natural language | Binary pass/fail: correct tool + task completion |
| **2** | Workflow | Multi-step pipelines (query → filter → summarize, ingest → validate, etc.) | Output correctness + method quality (LLM judge) |
| **3** | Discovery | Hypothesis-level: state a relationship as structured hypothesis (DiscoveryBench-style) | Faceted LLM judge + expert ground truth |

## Data Management Categories

1. Search: external/domain knowledge and literature
2. Data Discovery: locating datasets, files, or records in DSI repositories
3. Data Preparation: cleaning, validating, standardizing scientific data
4. Metadata Generation: structured documentation and provenance
5. Analysis & Summarization: interpreting, aggregating, synthesizing data

These are the DSI tools:

dsi_tools = [

                query_dsi_tool, 

                python_repl_tool, 

                load_dsi_tool, 

                download_file_tool, 

                arxiv_search_tool,

                wikipedia_search_tool,

                web_search_tool,

                send_email_tool,

                upload_paper_tool

## Setup

In [1]:
# Install dependencies into the active Jupyter kernel (run once)
%pip install -q -r requirements.txt
# --no-build-isolation: reuse the setuptools already in this kernel instead of pip
# fetching a fresh copy from PyPI for the build environment (avoids network/SSL
# failures on machines with restricted/proxied access to pypi.org).
%pip install -q --no-build-isolation -e ../..

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Load portal API key from portal_api_key.txt (see portal_api_key.txt.example)
import os
from pathlib import Path

_key_path = Path("portal_api_key.txt")
if not _key_path.is_file():
    raise FileNotFoundError(
        "Missing portal_api_key.txt — copy portal_api_key.txt.example and add your key."
    )
os.environ.setdefault("OPENAI_API_KEY", _key_path.read_text().strip())
os.environ["OPENAI_API_BASE"] = "https://aiportal-api.aws.lanl.gov"

In [3]:
import threading
import contextlib
import io
import json
import re
import sys
import time
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

import pandas as pd
from IPython.display import Markdown, display
from langchain_core.messages import AIMessage, HumanMessage, ToolMessage
from langchain_openai import ChatOpenAI

def find_ai_search_dir() -> Path:
    """Locate the tools/ai_search directory from cwd or any parent.

    Walks up the directory tree looking for dsi_explorer_agent.py so the
    notebook still works after the agent changes the process working directory.
    """
    for directory in (Path.cwd(), *Path.cwd().parents):
        if (directory / "dsi_explorer_agent.py").is_file():
            return directory.resolve()
        nested = directory / "tools" / "ai_search" / "dsi_explorer_agent.py"
        if nested.is_file():
            return nested.parent.resolve()
    raise RuntimeError("Could not find tools/ai_search — open this notebook from the dsi repo")

AI_SEARCH_DIR = find_ai_search_dir()
os.chdir(AI_SEARCH_DIR)

from dsi_explorer_agent import DSIExplorer, extract_message_texts
from tool_utils import reset_dsi_call_log, get_dsi_call_log

print(f"Working directory: {AI_SEARCH_DIR}")

Working directory: /Users/hhn/lanl/dsi/tools/ai_search

In [4]:
# --- Configuration ---
AI_PORTAL_BASE_URL = os.environ.get("OPENAI_API_BASE", "https://aiportal-api.aws.lanl.gov")

POSSIBLE_MODELS = [
    "aws-gov.gpt-5.4",
    "anthropic.claude-sonnet-4-5-20250929-v1:0",
    # "amazon.nova-pro-v1:0",
    # "meta.llama3-70b-instruct-v1:0",
    # "meta.llama3-8b-instruct-v1:0",
    # "mistral7b",
    # "llama3bv32instr",
    # "phi4",
    # "gpt-oss-120b",
    # "e5mistral7b",
    # "NVIDIA-Nemotron-3-Super-120B-A12B-FP8",
    # "gemma-4-31B-it",
]

LLM_MODEL = "aws-gov.gpt-5.4"   # default single model, used by make_explorer()/debug_task() when no llm is passed
JUDGE_MODEL = LLM_MODEL         # LLM judge for Level 2/3
MODELS_TO_RUN = list(POSSIBLE_MODELS)  # subset this to run the multi-model sweep against fewer models
TASK_TIMEOUT_SEC = 180           # max wall-clock seconds per agent turn before it's aborted as a timeout
USE_MCP = False                 # set True if levels_mcp_server.py is running on :8000
MCP_URL = "http://127.0.0.1:8000/mcp"
MASTER_DB = "data/oceans_11/ocean_11_datasets.db"

# NIF_DB = "data/oceans_11/nif.db"
# POISSON_DB = "data/oceans_11/poisson.db"

RESULTS_DIR = AI_SEARCH_DIR / "levels_benchmark_results"
RUN_ID = datetime.now().strftime("%Y%m%d_%H%M%S")

def make_llm(model_name: str, temperature: float = 0.1) -> ChatOpenAI:
    """Create a ChatOpenAI client pointed at the LANL AI portal."""
    return ChatOpenAI(
        model=model_name,
        api_key=os.environ["OPENAI_API_KEY"],
        base_url=AI_PORTAL_BASE_URL,
        temperature=temperature,
    )

llm_model = make_llm(LLM_MODEL)
judge_llm = make_llm(JUDGE_MODEL, temperature=0.0)
print(f"Using model: {LLM_MODEL} @ {AI_PORTAL_BASE_URL}")

Using model: aws-gov.gpt-5.4 @ https://aiportal-api.aws.lanl.gov

In [5]:
def make_explorer(llm: Optional[ChatOpenAI] = None) -> DSIExplorer:
    """Create a fresh DSIExplorer with a new workspace, thread, and master DB loaded.

    Resets cwd to AI_SEARCH_DIR first to avoid nested workspace folders on re-runs.
    Passes MCP settings when USE_MCP is True. Defaults to the global llm_model
    (LLM_MODEL) when no llm is given, so existing single-model calls keep working;
    pass a per-model client (e.g. make_llm(model_name)) to benchmark another model.
    """
    os.chdir(AI_SEARCH_DIR)  # avoid nested workspace folders on re-runs
    return DSIExplorer(
        llm=llm if llm is not None else llm_model,
        db_index_name=MASTER_DB,
        output_mode="jupyter",
        **({"use_mcp": True, "mcp_url": MCP_URL} if USE_MCP else {}),
    )

## Benchmark Harness

In [6]:
# Ground-truth constants for Level-1 quantitative checks
NIF_DATASET_ID = "3D FLASH Computation of National Ignition Facility Shot"


def canonicalize_db_path(path: str) -> str:
    """Normalize a DB path for exact Level-1 path matching."""
    s = Path(str(path)).as_posix()
    if "oceans_11/" in s:
        return s[s.index("oceans_11/") :]
    return Path(s).name


def _resolve_path_arg(call_args: Dict[str, Any]) -> str:
    """Resolve a load_dsi_tool 'path' arg the same way load_dsi() resolves it internally.

    Both models converged on passing the master/secondary DB's bare filename as `path`
    plus the folder as a separate `master_db_folder` kwarg (load_dsi_tool's own documented
    pattern for resolving relative paths against the master DB's folder) rather than a
    single joined string. Without this, canonicalize_db_path("nif.db") != canonicalize_db_path
    ("oceans_11/nif.db") even though the model loaded the exact right file.
    """
    path = str(call_args.get("path", ""))
    folder = call_args.get("master_db_folder")
    if folder and not Path(path).is_absolute():
        return str(Path(str(folder)) / path)
    return path


def _safe_model_label(model_name: str) -> str:
    """Sanitize a model name (which may contain ':', '.', '/') into a filename-safe label."""
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", model_name)


@dataclass
class BenchmarkTask:
    """Definition of a single benchmark task (query, rubric, and scoring hints)."""
    task_id: str
    level: int
    category: str
    query: str
    # Level 1 checks
    expected_tools: List[str] = field(default_factory=list)
    expected_args: Dict[str, Any] = field(default_factory=dict)
    expected_path: Optional[str] = None  # canonicalize and compare to tool arg "path"
    expected_count: Optional[int] = None  # must appear in tool result or response
    response_keywords: List[str] = field(default_factory=list)
    forbidden_keywords: List[str] = field(default_factory=list)
    reference_path: List[str] = field(default_factory=list)  # most-efficient human DSI CLI commands, for LLM-judged efficiency scoring
    setup_query: Optional[str] = None
    timeout_sec: Optional[float] = None  # per-task override; falls back to TASK_TIMEOUT_SEC when None
    # Level 2/3 rubric
    success_criteria: str = ""
    ground_truth_hypothesis: Optional[Dict[str, str]] = None
    requires_network: bool = False
    skip: bool = False


@dataclass
class TaskResult:
    """Outcome of running and scoring one benchmark task."""
    task_id: str
    level: int
    category: str
    query: str
    response: str
    tool_calls: List[Dict[str, Any]]
    elapsed_sec: float
    tokens: int
    passed: Optional[bool] = None
    score: Optional[float] = None
    judge_scores: Optional[Dict[str, Any]] = None
    notes: str = ""
    tool_results: List[str] = field(default_factory=list)
    dsi_calls: List[Dict[str, Any]] = field(default_factory=list)
    model: str = ""  # which LLM produced this result; set by run_benchmark/run_benchmark_all_models


def extract_tool_calls(result: dict) -> List[Dict[str, Any]]:
    """Collect tool names and args from all AIMessage tool_calls in an agent result."""
    calls = []
    for msg in result.get("messages", []):
        if isinstance(msg, AIMessage) and msg.tool_calls:
            for tc in msg.tool_calls:
                calls.append({"name": tc.get("name"), "args": tc.get("args", {})})
    return calls


def extract_tool_results(result: dict) -> List[str]:
    """Collect ToolMessage contents as strings for quantitative Level-1 checks."""
    out = []
    for msg in result.get("messages", []):
        if isinstance(msg, ToolMessage):
            content = msg.content
            if isinstance(content, (list, dict)):
                out.append(json.dumps(content, default=str))
            else:
                out.append(str(content))
    return out


def format_dsi_call_log(dsi_calls: List[Dict[str, Any]]) -> str:
    """Pretty-print recorded DSI Python API calls (method, args, kwargs, timing)."""
    if not dsi_calls:
        return "(no DSI API calls)"
    lines = []
    for i, call in enumerate(dsi_calls, 1):
        lines.append(
            f"[{i}] DSI.{call['method']}("
            f"{', '.join(call.get('args', []))}"
            f"{', ' if call.get('args') and call.get('kwargs') else ''}"
            f"{', '.join(f'{k}={v}' for k, v in call.get('kwargs', {}).items())})"
            f"  [{call.get('elapsed_sec', 0):.3f}s]"
            + (f"  ERROR: {call['error']}" if call.get("error") else "")
        )
    return "\n".join(lines)


class TaskTimeoutError(TimeoutError):
    """Raised when a single agent invocation exceeds its allotted timeout."""


def invoke_agent(explorer: DSIExplorer, query: str, timeout: Optional[float] = None) -> dict:
    """Send one user query through the agent graph and return the raw result dict.

    Uses async invoke when MCP is enabled; otherwise sync invoke. Adds _elapsed
    seconds to the result for timing metrics.

    The (blocking) invoke call runs on a daemon thread; if it doesn't finish
    within `timeout` seconds (defaults to TASK_TIMEOUT_SEC), TaskTimeoutError is
    raised so a stuck/slow model can't hang the whole benchmark sweep. Python
    cannot forcibly kill a running thread, so the abandoned call keeps running
    in the background — but because the thread is a daemon, it won't block the
    notebook kernel process from exiting/restarting later, and this function
    itself returns control immediately once `timeout` elapses either way.

    Any stdout/stderr the worker thread writes is captured into a buffer
    instead of going to the real stdout from a background thread. ipykernel
    routes stream output to the currently-executing cell using a parent-header
    that gets confused by concurrent writes from multiple threads; left
    unguarded this silently drops/misattributes *later* print() calls made on
    the main thread (e.g. the "Tools called"/"DSI API calls" lines), which is
    why they tend to stop showing up starting with the second model in a
    multi-model sweep. The buffer is replayed on the main thread right after
    `join()` returns, so only the main thread ever touches the real stdout.
    """
    start = time.time()
    msg = explorer.craft_message(query)
    timeout = TASK_TIMEOUT_SEC if timeout is None else timeout

    box: Dict[str, Any] = {}

    def _invoke():
        buf = io.StringIO()
        try:
            with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(buf):
                if explorer.use_mcp:
                    from dsi_explorer_agent import run_async
                    box["result"] = run_async(explorer.app.ainvoke(
                        msg, config={"configurable": {"thread_id": explorer.thread_id}}
                    ))
                else:
                    box["result"] = explorer.app.invoke(
                        msg, config={"configurable": {"thread_id": explorer.thread_id}}
                    )
        except Exception as e:
            box["error"] = e
        finally:
            box["captured_output"] = buf.getvalue()

    worker = threading.Thread(target=_invoke, daemon=True)
    worker.start()
    worker.join(timeout=timeout)
    if worker.is_alive():
        raise TaskTimeoutError(f"Agent call exceeded {timeout}s timeout for query: {query[:80]!r}")

    captured = box.get("captured_output", "")
    if captured:
        sys.stdout.write(captured)
        sys.stdout.flush()

    if "error" in box:
        raise box["error"]

    result = box["result"]
    result["_elapsed"] = time.time() - start
    return result


def run_task(explorer: DSIExplorer, task: BenchmarkTask, verbose: bool = True) -> TaskResult:
    """Execute one benchmark task and capture response, tool calls, and timing.

    Runs setup_query first when present (e.g. load a DB before the main query).
    Skipped tasks return immediately with notes='skipped'.
    """
    if task.skip:
        return TaskResult(task.task_id, task.level, task.category, task.query,
                          "", [], 0.0, 0, passed=None, notes="skipped")

    reset_dsi_call_log()

    if task.setup_query:
        invoke_agent(explorer, task.setup_query, timeout=task.timeout_sec)

    if verbose:
        display(Markdown(f"### `{task.task_id}` — Level {task.level} / {task.category}\n\n**Query:** {task.query}"))

    result = invoke_agent(explorer, task.query, timeout=task.timeout_sec)
    response = (result.get("response") or "").strip()
    tool_calls = extract_tool_calls(result)
    tool_results = extract_tool_results(result)
    dsi_calls = get_dsi_call_log()
    tokens = result.get("metadata", {}).get("token_usage", {}).get("total_tokens", 0)

    if verbose:
        display(Markdown(response))
        print(f"Tools called: {[t['name'] for t in tool_calls]} | {result['_elapsed']:.1f}s | {tokens} tokens")
        print(f"DSI API calls: {[c['method'] for c in dsi_calls]}")

    return TaskResult(
        task_id=task.task_id,
        level=task.level,
        category=task.category,
        query=task.query,
        response=response,
        tool_calls=tool_calls,
        elapsed_sec=result["_elapsed"],
        tokens=tokens,
        tool_results=tool_results,
        dsi_calls=dsi_calls,
    )


def score_level1(task: BenchmarkTask, result: TaskResult) -> TaskResult:
    """Score a Level 1 (atomic) task with binary pass/fail heuristics.

    Checks: expected tool, expected args (exact), canonicalized path, quantitative
    count in tool results/response, keywords / forbidden keywords, max tool calls.
    """
    tool_names = [t["name"] for t in result.tool_calls]
    matching_calls = [t for t in result.tool_calls if t["name"] in (task.expected_tools or tool_names)]
    notes = []

    tool_ok = True
    if task.expected_tools:
        tool_ok = any(t in tool_names for t in task.expected_tools)
        if not tool_ok:
            notes.append(f"Expected one of {task.expected_tools}, got {tool_names}")

    args_ok = True
    if task.expected_args and tool_ok:
        args_ok = False

        def _arg_match(call_args: Dict[str, Any], key: str, want: Any) -> bool:
            if key == "path":
                return canonicalize_db_path(_resolve_path_arg(call_args)) == canonicalize_db_path(str(want))
            return str(call_args.get(key)) == str(want)

        for call in matching_calls:
            if all(_arg_match(call["args"], k, v) for k, v in task.expected_args.items()):
                args_ok = True
                break
        if not args_ok:
            notes.append(
                f"Expected args {task.expected_args}, got "
                f"{[c['args'] for c in matching_calls]}"
            )

    path_ok = True
    if task.expected_path is not None and tool_ok:
        path_ok = False
        want = canonicalize_db_path(task.expected_path)
        for call in matching_calls:
            got = _resolve_path_arg(call["args"])
            if got and canonicalize_db_path(got) == want:
                path_ok = True
                break
        if not path_ok:
            notes.append(
                f"Expected canonical path {want}, got "
                f"{[c['args'].get('path') for c in matching_calls]}"
            )

    quant_ok = True
    if task.expected_count is not None:
        blob = " ".join(result.tool_results + [result.response])
        # Prefer structured count keys, then bare integer token.
        patterns = [
            rf'["\']?(?:count|missing_count)["\']?\s*[:=]\s*{task.expected_count}\b',
            rf"\b{task.expected_count}\b",
        ]
        quant_ok = any(re.search(p, blob) for p in patterns)
        if not quant_ok:
            notes.append(f"Expected count {task.expected_count} not found in tool results/response")

    keyword_ok = True
    response_lower = result.response.lower()
    tools_blob = " ".join(result.tool_results).lower() + " " + response_lower
    if task.response_keywords:
        keyword_ok = any(kw.lower() in tools_blob for kw in task.response_keywords)
        if not keyword_ok:
            notes.append(f"Response missing keywords: {task.response_keywords}")

    forbidden_ok = True
    if task.forbidden_keywords:
        hits = [kw for kw in task.forbidden_keywords if kw.lower() in tools_blob]
        if hits:
            forbidden_ok = False
            notes.append(f"Forbidden distractors present: {hits}")

    # Atomic tools may return short structured answers; allow short responses when tools ran.
    nonempty = len(result.response.strip()) > 0 or bool(result.tool_calls)
    if not nonempty:
        notes.append("Response too short or empty")

    result.passed = all(
        [tool_ok, args_ok, path_ok, quant_ok, keyword_ok, forbidden_ok, nonempty]
    )
    result.score = 1.0 if result.passed else 0.0
    result.notes = "; ".join(notes)
    return result


def llm_judge(prompt: str) -> dict:
    """Ask the judge LLM to score a task and parse JSON from its response.

    Falls back to {"raw": text} if the model returns non-JSON output.
    """
    resp = judge_llm.invoke(prompt)
    text = resp.content.strip()
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass
    return {"raw": text}


def score_efficiency(task: BenchmarkTask, result: TaskResult) -> TaskResult:
    """LLM-judge how efficiently the agent solved the task vs. the human reference CLI path.

    Uses task.reference_path (the most-efficient sequence of DSI CLI commands, written by a
    human) as the gold standard, and compares it against the agent's actual tool_calls and
    dsi_calls. The verdict is stored in result.judge_scores so it auto-flattens into the
    results dataframe as judge_efficiency_score / judge_efficiency_reasoning, alongside (and
    independent of) the binary correctness score from score_level1. Tasks with no
    reference_path are skipped (left unscored for efficiency).
    """
    if not task.reference_path:
        return result

    agent_tool_calls = [f"{c['name']}({c['args']})" for c in result.tool_calls]
    agent_dsi_calls = [
        f"{c['method']}({', '.join(c.get('args', []))})" for c in result.dsi_calls
    ]

    prompt = f"""You are judging the EFFICIENCY of an AI agent's path for a data-management task,
against the most efficient path a human expert would take at the DSI command line.

Task: {task.query}

Reference path (ground truth, most efficient -- one command per line):
{chr(10).join(task.reference_path)}

Agent's actual tool calls (in order):
{json.dumps(agent_tool_calls, indent=2)}

Agent's actual underlying DSI API calls (in order):
{json.dumps(agent_dsi_calls, indent=2)}

Score the agent's efficiency from 0.0 (far less efficient than the reference -- redundant
queries, unnecessary exploration, retries, or extra DSI calls beyond what the reference
path needed) to 1.0 (matched the reference path's number of essential steps with no waste).
A correct final answer reached via a wasteful path should still score low here.

Respond with ONLY JSON: {{"efficiency_score": <float 0.0-1.0>, "reasoning": "<one sentence>"}}
"""
    verdict = llm_judge(prompt)
    result.judge_scores = result.judge_scores or {}
    result.judge_scores["efficiency_score"] = verdict.get("efficiency_score")
    result.judge_scores["efficiency_reasoning"] = verdict.get("reasoning", verdict.get("raw", ""))
    return result


def score_task(task: BenchmarkTask, result: TaskResult) -> TaskResult:
    """Route a TaskResult to the scorer for its complexity level, then layer on efficiency."""
    if task.level == 1:
        result = score_level1(task, result)
    # elif task.level == 2:
    #     result = score_level2(task, result)
    # else:
    #     result = score_level3(task, result)
    return score_efficiency(task, result)


def run_benchmark(
    tasks: List[BenchmarkTask],
    *,
    isolated: bool = False,
    llm: Optional[ChatOpenAI] = None,
    model_label: str = "",
) -> List[TaskResult]:
    """Run and score a list of tasks, printing PASS/FAIL/SKIP for each.

    When isolated=True (Level 1), each task gets a fresh explorer so prior
    conversation state does not affect the next task. When isolated=False,
    all tasks share one explorer (useful for Level 2/3 workflow continuity).

    Pass `llm` (e.g. make_llm(model_name)) to benchmark a specific model instead
    of the global default; `model_label` is stamped onto every TaskResult so
    results from different models can be told apart and compared afterward.

    Tasks with requires_network are skipped when LEVELS_SKIP_NETWORK=1. Any task
    that raises is caught and recorded as a failed TaskResult instead of aborting
    the rest of the sweep — this includes TaskTimeoutError when a task exceeds
    its timeout_sec / TASK_TIMEOUT_SEC, and other errors (e.g. a model that
    errors on tool-calling).
    """
    results = []
    explorer = None if isolated else make_explorer(llm=llm)
    for task in tasks:
        if task.requires_network and os.environ.get("LEVELS_SKIP_NETWORK", "0") == "1":
            task = BenchmarkTask(**{**asdict(task), "skip": True})
        task_explorer = make_explorer(llm=llm) if isolated else explorer
        task_timeout = task.timeout_sec if task.timeout_sec is not None else TASK_TIMEOUT_SEC
        try:
            tr = run_task(task_explorer, task)
            tr = score_task(task, tr)
        except TaskTimeoutError as e:
            tr = TaskResult(
                task_id=task.task_id, level=task.level, category=task.category, query=task.query,
                response="", tool_calls=[], elapsed_sec=task_timeout, tokens=0,
                passed=False, score=0.0, notes=f"timeout: {e}",
            )
        except Exception as e:
            tr = TaskResult(
                task_id=task.task_id, level=task.level, category=task.category, query=task.query,
                response="", tool_calls=[], elapsed_sec=0.0, tokens=0,
                passed=False, score=0.0, notes=f"error: {e!r}",
            )
        tr.model = model_label
        results.append(tr)
        prefix = f"{model_label} | " if model_label else ""
        if tr.notes == "skipped":
            status = "SKIP"
        elif tr.notes.startswith("timeout:"):
            status = "TIMEOUT"
        elif tr.passed:
            status = "PASS"
        else:
            status = "FAIL"
        print(f"[{status}] {prefix}{tr.task_id} — score={tr.score}\n")
    return results


def results_to_dataframe(results: List[TaskResult]) -> pd.DataFrame:
    """Flatten TaskResult objects into a summary DataFrame for display and analysis."""
    rows = []
    for r in results:
        row = {
            "model": r.model,
            "task_id": r.task_id,
            "level": r.level,
            "category": r.category,
            "passed": r.passed,
            "score": r.score,
            "elapsed_sec": round(r.elapsed_sec, 1),
            "tokens": r.tokens,
            "tools": ", ".join(t["name"] for t in r.tool_calls),
            "notes": r.notes,
        }
        if r.judge_scores:
            for k, v in r.judge_scores.items():
                if isinstance(v, (int, float, str, bool)):
                    row[f"judge_{k}"] = v
        rows.append(row)
    return pd.DataFrame(rows)


def save_results(results: List[TaskResult], label: str) -> Path:
    """Write benchmark results to levels_benchmark_results/{RUN_ID}_{label}.json."""
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    out = RESULTS_DIR / f"{RUN_ID}_{label}.json"
    payload = [asdict(r) for r in results]
    out.write_text(json.dumps(payload, indent=2, default=str))
    print(f"Saved: {out}")
    return out

def format_dsi_call_log(dsi_calls: List[Dict[str, Any]]) -> str:
    """Pretty-print recorded DSI Python API calls (method, args, kwargs, timing)."""
    if not dsi_calls:
        return "(no DSI API calls)"
    lines = []
    for i, call in enumerate(dsi_calls, 1):
        lines.append(
            f"[{i}] DSI.{call['method']}("
            f"{', '.join(call.get('args', []))}"
            f"{', ' if call.get('args') and call.get('kwargs') else ''}"
            f"{', '.join(f'{k}={v}' for k, v in call.get('kwargs', {}).items())})"
            f"  [{call.get('elapsed_sec', 0):.3f}s]"
            + (f"  ERROR: {call['error']}" if call.get("error") else "")
        )
    return "\n".join(lines)

## Task Catalog

Tasks are drawn from the example queries in `dsi_data_explorer.ipynb`, `dsi_data_explorer-poisson.ipynb`, and `dsi_code_run.ipynb`.

In [7]:
# Level 1 — Atomic (single tool call, binary pass/fail + quantitative checks)
# Load data, store data, query data, extract data, search data, download data
#
# Each task's `reference_path` is the most-efficient sequence of DSI CLI commands a human
# would run to answer the same query. score_efficiency() LLM-judges the agent's actual
# tool_calls/dsi_calls against this reference to produce a judge_efficiency_score,
# independent of the binary correctness score from score_level1.

LEVEL1_TASKS = [
    BenchmarkTask(
        task_id="L1_load_ocean11",
        level=1, category="Data Discovery",
        query="Load the ocean_11_datasets.db database.",
        expected_tools=["load_dsi_tool"],
        expected_path= "oceans_11/ocean_11_datasets.db",
        expected_args={"path": "oceans_11/ocean_11_datasets.db"},
        reference_path=["read /Users/hhn/lanl/dsi/tools/ai_search/oceans11.db"],
    ),
    BenchmarkTask(
        task_id="L1_load_nif_direct",
        level=1, category="Data Discovery",
        query="Load the nif.db database.",
        expected_tools=["load_dsi_tool"],
        expected_path="oceans_11/nif.db",
        expected_args={"path": "oceans_11/nif.db"},
        reference_path=["read data/oceans_11/nif.db"],
    ),
    BenchmarkTask(
        task_id="L1_load_poisson",
        level=1, category="Data Discovery",
        query="Load the poisson.db database.",
        expected_tools=["load_dsi_tool"],
        expected_path="oceans_11/poisson.db",
        expected_args={"path": "oceans_11/poisson.db"},
        reference_path=["read data/oceans_11/poisson.db"],
    ),
    BenchmarkTask(
        task_id="L1_search_implosion",
        level=1, category="Search",
        query="Do you have any implosion data in oceans 11 database?",
        expected_tools=["query_dsi_tool"],
        response_keywords=["National Ignition", "NIF", "FLASH"],
        forbidden_keywords=["Bowtie", "Deep Water Impact"],
        reference_path=[
            "read /Users/hhn/lanl/dsi/tools/ai_search/oceans11.db",
            "search oceans11 implosion",
        ],
    ),
    BenchmarkTask(
        task_id="L1_download_nif_sim",
        level=1, category="Data Preparation",
        query="Download the simulation data for sim name: nifcylxyz_hdf5_plt_cnt_0000.flash",
        expected_tools=["download_file_tool"],
        expected_args={"url": "https://oceans11.lanl.gov/nif/N210201-001_3D_r2//nifcylxyz_hdf5_plt_cnt_0000.flash"},
        requires_network=True,
        reference_path=[
            "read data/oceans_11/ocean_11_datasets.db",
            "query \"SELECT Title, dsi_database FROM genesis_datacard WHERE Title LIKE '%NIF%' OR Title LIKE '%FLASH%'\"",
            "read data/oceans_11/nif.db",
            "query \"SELECT sim_name, link FROM nif_metadata WHERE sim_name LIKE '%nifcylxyz_hdf5_plt_cnt_0000%'\"",
            "pull_data url nif_sim https://oceans11.lanl.gov/nif/N210201-001_3D_r2//nifcylxyz_hdf5_plt_cnt_0000.flash",
        ],
    ),
    BenchmarkTask(
        task_id="L1_store_poisson_hdf5",
        level=1, category="Data Preparation",
        query="Download this simulation data file: https://oceans11.lanl.gov/electrostaticEquations/LA-UR-25-29606-electrostatic_dataset_1k/data/electrostatic_poisson_32x32_1-1000.hdf5",
        expected_tools=["download_file_tool"],
        expected_args={"url": "https://oceans11.lanl.gov/electrostaticEquations/LA-UR-25-29606-electrostatic_dataset_1k/data/electrostatic_poisson_32x32_1-1000.hdf5"},
        requires_network=True,
        reference_path=[
            "pull_data url poisson_hdf5 https://oceans11.lanl.gov/electrostaticEquations/LA-UR-25-29606-electrostatic_dataset_1k/data/electrostatic_poisson_32x32_1-1000.hdf5",
        ],
    ),
    BenchmarkTask(
        task_id="L1_owner_field",
        level=1, category="Metadata Query",
        query=f'Who is the owner of the NIF dataset"',
        expected_tools=["query_dsi_tool"],
        response_keywords=["Joshua", "Paul", "Sauppe"],
        reference_path=[
            "read data/oceans_11/ocean_11_datasets.db",
            "query \"SELECT Title, Contact_Point_, Email FROM genesis_datacard WHERE Title LIKE '%NIF%' OR Title LIKE '%FLASH%'\"",
        ],
    ),
    BenchmarkTask(
        task_id="L1_extract_dataset_count",
        level=1, category="Data Query",
        query="How many datasets are in the Ocean 11 catalog?",
        expected_tools=["query_dsi_tool"],
        expected_count=9,
        reference_path=[
            "read data/oceans_11/ocean_11_datasets.db",
            'query "SELECT COUNT(*) FROM genesis_datacard"',
        ],
    ),
    BenchmarkTask(
        task_id="L1_extract_originating_org",
        level=1, category="Metadata Query",
        query="What organization is listed for the Ocean 11 datasets?",
        expected_tools=["query_dsi_tool"],
        response_keywords=["DOE", "LANL"],
        reference_path=[
            "read data/oceans_11/ocean_11_datasets.db",
            'query "SELECT DISTINCT Originating_Organization FROM genesis_datacard"',
        ],
    ),
    BenchmarkTask(
        task_id="L1_extract_physics_theme_count",
        level=1, category="Data Query",
        query="How many datasets are categorized as physics?",
        expected_tools=["query_dsi_tool"],
        expected_count=5,
        reference_path=[
            "read data/oceans_11/ocean_11_datasets.db",
            "query \"SELECT COUNT(*) FROM genesis_datacard WHERE LOWER(\\\"Theme/Category_:_Domain\\\") = 'physics'\"",
        ],
    ),
    BenchmarkTask(
        task_id="L1_nif_domain_extent",
        level=1, category="Data Query",
        query="What are the spatial bounds of the NIF simulation's computational domain?",
        expected_tools=["query_dsi_tool"],
        response_keywords=["3.072"],
        reference_path=[
            "read data/oceans_11/ocean_11_datasets.db",
            "search computational domain",
        ],
    ),
    BenchmarkTask(
        task_id="L1_nif_timestep_count",
        level=1, category="Data Query",
        query="How many discrete timesteps of the NIF simulation are recorded in NIF.",
        expected_tools=["query_dsi_tool"],
        expected_count=20,
        reference_path=[
            "read data/oceans_11/nif.db",
            'query "SELECT COUNT(DISTINCT timestep) FROM nif_metadata"',
        ],
    ),
    BenchmarkTask(
        task_id="L1_nif_array_field_count",
        level=1, category="Data Query",
        query="How many distinct physical quantity arrays are recorded per simulation timestep in NIF.",
        expected_tools=["query_dsi_tool"],
        expected_count=9,
        response_keywords=["dens", "pres"],
        reference_path=[
            "read data/oceans_11/nif.db",
            'query "SELECT * FROM array_and_types"',
        ],
    ),
    # cd tools/ai_search
    # dsi
    # dsi> search dens
    # dsi> search dens_max *returns no results*
    # Too complicated for level 1
    # BenchmarkTask(
    #     task_id="L1_dens_max_units",
    #     level=1, category="Metadata Generation",
    #     query="What unit is dens_max recorded in?",
    #     expected_tools=["query_dsi_tool"],
    #     response_keywords=["g/cm"],
    # ),

]

ALL_TASKS = list(LEVEL1_TASKS)

## Run Benchmarks

Set environment variable `LEVELS_SKIP_NETWORK=1` to skip tasks that require external network access.

In [8]:
def run_level(
    label: str,
    tasks: List[BenchmarkTask],
    *,
    llm: Optional[ChatOpenAI] = None,
    model_label: str = "",
) -> List[TaskResult]:
    """Run one complexity level end-to-end: benchmark all tasks and save JSON.

    Pass `llm`/`model_label` to run this level against a specific model (see
    run_benchmark_all_models below to sweep across every model in POSSIBLE_MODELS).
    """
    heading = f"## Running {label}"
    if model_label:
        heading += f" — model: `{model_label}`"
    heading += f" ({len(tasks)} tasks)"
    display(Markdown(heading))
    isolated = all(t.level == 1 for t in tasks)
    results = run_benchmark(tasks, isolated=isolated, llm=llm, model_label=model_label)
    save_label = f"{label}__{_safe_model_label(model_label)}" if model_label else label
    save_results(results, save_label)
    return results


def run_benchmark_all_models(
    tasks: List[BenchmarkTask],
    models: Optional[List[str]] = None,
    level_label: str = "level1_atomic",
) -> Dict[str, List[TaskResult]]:
    """Run the given tasks once per model so results are directly comparable.

    Creates a fresh ChatOpenAI client (make_llm) and fresh DSIExplorer(s) for each
    model via run_level -> run_benchmark, so no state leaks between models. If a
    model fails to even construct (auth error, unknown/unsupported model name,
    etc.) before any task can run, it is recorded as a failed TaskResult for every
    task in `tasks` rather than aborting the whole sweep — individual per-task
    errors are already handled inside run_benchmark. Saves one results JSON per
    model plus a combined JSON with everything.
    """
    models = models or MODELS_TO_RUN
    all_model_results: Dict[str, List[TaskResult]] = {}

    for model_name in models:
        try:
            model_llm = make_llm(model_name)
            results = run_level(level_label, tasks, llm=model_llm, model_label=model_name)
        except Exception as e:
            print(f"[ERROR] Model `{model_name}` failed entirely: {e!r}\n")
            results = [
                TaskResult(
                    task_id=t.task_id, level=t.level, category=t.category, query=t.query,
                    response="", tool_calls=[], elapsed_sec=0.0, tokens=0,
                    passed=False, score=0.0, notes=f"model_error: {e!r}", model=model_name,
                )
                for t in tasks
            ]
        all_model_results[model_name] = results

    combined = [r for model_results in all_model_results.values() for r in model_results]
    save_results(combined, f"{level_label}__all_models")
    return all_model_results

### Level 1 — Atomic

In [9]:
# Runs LEVEL1_TASKS once per model in MODELS_TO_RUN (defaults to POSSIBLE_MODELS),
# each with its own fresh ChatOpenAI client + DSIExplorer(s), so results are comparable.
# Set LEVELS_SKIP_NETWORK=1 beforehand to skip requires_network tasks for every model.
l1_model_results = run_benchmark_all_models(LEVEL1_TASKS, MODELS_TO_RUN, level_label="level1_atomic")

# Flatten into one dataframe, tagged by model, for side-by-side comparison
l1_results = [r for results in l1_model_results.values() for r in results]
l1_df = results_to_dataframe(l1_results)
display(l1_df)

## Running level1_atomic — model: `aws-gov.gpt-5.4` (13 tasks)

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_33

### `L1_load_ocean11` — Level 1 / Data Discovery

**Query:** Load the ocean_11_datasets.db database.

Loaded `/Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/ocean_11_datasets.db`.

Tools called: ['load_dsi_tool'] | 3.2s | 2292 tokens
DSI API calls: ['__init__', 'list', 'close', '__init__', 'list', 'close', '__init__', 'list', 'schema', 'close']
[PASS] aws-gov.gpt-5.4 | L1_load_ocean11 — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_33

### `L1_load_nif_direct` — Level 1 / Data Discovery

**Query:** Load the nif.db database.

Loaded `nif.db`.

Current database:
`/Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/nif.db`

Tools called: ['load_dsi_tool'] | 2.6s | 1922 tokens
DSI API calls: ['__init__', 'list', 'close', '__init__', 'list', 'close', '__init__', 'list', 'schema', 'close']
[PASS] aws-gov.gpt-5.4 | L1_load_nif_direct — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_33

### `L1_load_poisson` — Level 1 / Data Discovery

**Query:** Load the poisson.db database.

Loaded `/Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/poisson.db`.

Tools called: ['load_dsi_tool'] | 2.9s | 2016 tokens
DSI API calls: ['__init__', 'list', 'close', '__init__', 'list', 'close', '__init__', 'list', 'schema', 'close']
[PASS] aws-gov.gpt-5.4 | L1_load_poisson — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_33

### `L1_search_implosion` — Level 1 / Search

**Query:** Do you have any implosion data in oceans 11 database?

Yes — there is at least one implosion-related entry in the Oceans 11 database:

- 3D FLASH Computation of National Ignition Facility Shot
  - Domain: fusion
  - Keywords: NIF, fusion, 3d, simulation
  - Summary: 3D FLASH simulation of a cylindrical implosion experiment at the National Ignition Facility, with 61 HDF5 time outputs from 0 to 30 ns.
  - Associated dataset: nif.db

If you want, I can also load `nif.db` and check what actual data tables it contains.

Tools called: ['query_dsi_tool'] | 3.9s | 2376 tokens
DSI API calls: ['__init__', 'query', 'close']
[PASS] aws-gov.gpt-5.4 | L1_search_implosion — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_33

### `L1_download_nif_sim` — Level 1 / Data Preparation

**Query:** Download the simulation data for sim name: nifcylxyz_hdf5_plt_cnt_0000.flash

I couldn’t find a matching entry for `nifcylxyz_hdf5_plt_cnt_0000.flash` in the current database, so I don’t have a download URL or file path to fetch it from.

If you want, I can:
1. search for close matches to that simulation name, or
2. list entries containing `nifcylxyz` or `flash` and then download the correct one.

Tools called: ['query_dsi_tool'] | 3.7s | 1838 tokens
DSI API calls: ['__init__', 'query', 'close']
[FAIL] aws-gov.gpt-5.4 | L1_download_nif_sim — score=0.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_33

### `L1_store_poisson_hdf5` — Level 1 / Data Preparation

**Query:** Download this simulation data file: https://oceans11.lanl.gov/electrostaticEquations/LA-UR-25-29606-electrostatic_dataset_1k/data/electrostatic_poisson_32x32_1-1000.hdf5

Downloaded successfully:

`/Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_33/electrostatic_poisson_32x32_1-1000.hdf5`

Tools called: ['download_file_tool'] | 2.9s | 1933 tokens
DSI API calls: []
[PASS] aws-gov.gpt-5.4 | L1_store_poisson_hdf5 — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_33

### `L1_owner_field` — Level 1 / Metadata Query

**Query:** Who is the owner of the NIF dataset"

I found the NIF entry owner/contact as:

- Contact point: **NIF Data Management Team**
- Email: **nif-data@llnl.gov**
- Originating organization: **Lawrence Livermore National Laboratory**

If you want, I can also pull the full NIF dataset record.

Tools called: ['query_dsi_tool'] | 3.5s | 1791 tokens
DSI API calls: ['__init__', 'query', 'close']
[FAIL] aws-gov.gpt-5.4 | L1_owner_field — score=0.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_34

### `L1_extract_dataset_count` — Level 1 / Data Query

**Query:** How many datasets are in the Ocean 11 catalog?

There are 9 datasets in the Ocean 11 catalog.

Tools called: ['query_dsi_tool'] | 3.1s | 1748 tokens
DSI API calls: ['__init__', 'query', 'close']
[PASS] aws-gov.gpt-5.4 | L1_extract_dataset_count — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_34

### `L1_extract_originating_org` — Level 1 / Metadata Query

**Query:** What organization is listed for the Ocean 11 datasets?

The listed organization is DOE:LANL.

Tools called: ['query_dsi_tool'] | 2.0s | 1776 tokens
DSI API calls: ['__init__', 'query', 'close']
[PASS] aws-gov.gpt-5.4 | L1_extract_originating_org — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_34

### `L1_extract_physics_theme_count` — Level 1 / Data Query

**Query:** How many datasets are categorized as physics?

5 datasets are categorized as physics.

Tools called: ['query_dsi_tool'] | 2.0s | 1753 tokens
DSI API calls: ['__init__', 'query', 'close']
[PASS] aws-gov.gpt-5.4 | L1_extract_physics_theme_count — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_34

### `L1_nif_domain_extent` — Level 1 / Data Query

**Query:** What are the spatial bounds of the NIF simulation's computational domain?

The NIF simulation uses a cubic computational domain with

- x: -3.072 mm to 3.072 mm
- y: -3.072 mm to 3.072 mm
- z: -3.072 mm to 3.072 mm

So the spatial bounds are:
(x, y, z) ∈ [-3.072 mm, 3.072 mm] in each dimension.

Tools called: ['query_dsi_tool'] | 3.4s | 2405 tokens
DSI API calls: ['__init__', 'query', 'close']
[PASS] aws-gov.gpt-5.4 | L1_nif_domain_extent — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_34

### `L1_nif_timestep_count` — Level 1 / Data Query

**Query:** How many discrete timesteps of the NIF simulation are recorded in NIF.

The NIF simulation records 61 discrete timesteps.

The dataset description states the outputs span 0 ns to 30 ns at 0.5 ns intervals, which also gives:
\[
(30 - 0)/0.5 + 1 = 61
\]

Tools called: ['query_dsi_tool', 'query_dsi_tool'] | 4.5s | 3604 tokens
DSI API calls: ['__init__', 'query', 'close', '__init__', 'query', 'close']
[FAIL] aws-gov.gpt-5.4 | L1_nif_timestep_count — score=0.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_34

### `L1_nif_array_field_count` — Level 1 / Data Query

**Query:** How many distinct physical quantity arrays are recorded per simulation timestep in NIF.

9 distinct physical quantity arrays are recorded per simulation timestep in the NIF dataset.

Tools called: ['query_dsi_tool', 'load_dsi_tool', 'query_dsi_tool'] | 4.4s | 2652 tokens
DSI API calls: ['__init__', 'query', 'close', '__init__', 'list', 'close', '__init__', 'list', 'close', '__init__', 'list', 'schema', 'close', '__init__', 'query', 'close']
[PASS] aws-gov.gpt-5.4 | L1_nif_array_field_count — score=1.0

Saved: /Users/hhn/lanl/dsi/tools/ai_search/levels_benchmark_results/20260805_193326_level1_atomic__aws-gov.gpt-5.4.json

## Running level1_atomic — model: `anthropic.claude-sonnet-4-5-20250929-v1:0` (13 tasks)

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_34

### `L1_load_ocean11` — Level 1 / Data Discovery

**Query:** Load the ocean_11_datasets.db database.

The ocean_11_datasets.db database has been successfully loaded.

The database contains a **genesis_datacard** table with information about 11 resources in the Ocean 11 dataset. Each record includes metadata such as title, keywords, description, contact information, security classification, and a path to an associated DSI database that can be loaded for further analysis.

Tools called: ['load_dsi_tool'] | 5.0s | 3632 tokens
DSI API calls: ['__init__', 'list', 'close', '__init__', 'list', 'close', '__init__', 'list', 'schema', 'close']
[PASS] anthropic.claude-sonnet-4-5-20250929-v1:0 | L1_load_ocean11 — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_34

### `L1_load_nif_direct` — Level 1 / Data Discovery

**Query:** Load the nif.db database.

The **nif.db** database has been loaded successfully.

**Schema:**
- **array_and_types**: Contains array names and their types.
- **nif_metadata**: Contains simulation metadata including simulation name, timestep, number of arrays, shape, and min/max values for various physical quantities (ablation, chamber, density, deposition, foam, mark, pressure, electron temperature, ion temperature), plus a link field.

Tools called: ['load_dsi_tool'] | 4.8s | 3252 tokens
DSI API calls: ['__init__', 'list', 'close', '__init__', 'list', 'close', '__init__', 'list', 'schema', 'close']
[PASS] anthropic.claude-sonnet-4-5-20250929-v1:0 | L1_load_nif_direct — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_34

### `L1_load_poisson` — Level 1 / Data Discovery

**Query:** Load the poisson.db database.

The **poisson.db** database has been loaded successfully.

**Schema:**
- Table: `poisson`
- Fields: `name`, `LAUR`, `example`, `environment`, `argements`, `data`, `statistics`

**Description:**
This is a 1000-record HDF5 dataset generated from simulations implementing Poisson's equations for electrostatics. The table contains URLs to documentation (PDF), example images (PNG), environment configuration (YAML), the actual HDF5 data file, and global statistics (JSON).

Tools called: ['load_dsi_tool'] | 5.4s | 3359 tokens
DSI API calls: ['__init__', 'list', 'close', '__init__', 'list', 'close', '__init__', 'list', 'schema', 'close']
[PASS] anthropic.claude-sonnet-4-5-20250929-v1:0 | L1_load_poisson — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_34

### `L1_search_implosion` — Level 1 / Search

**Query:** Do you have any implosion data in oceans 11 database?

Yes! The Ocean 11 database contains implosion data:

**3D FLASH Computation of National Ignition Facility Shot**

This dataset contains 3D radiation-hydrodynamics simulation data of a **cylindrical implosion experiment** performed at the National Ignition Facility (NIF shot N210201-001).

Key details:
- **Simulation code**: FLASH (open-access radiation-hydrodynamics code)
- **Time range**: 0-30 nanoseconds (61 HDF5 output files, every 0.5 ns)
- **Domain**: Cubic domain extending over (x,y,z) = [-3.072 mm, 3.072 mm]
- **Resolution**: Minimum cell size of 8 microns with adaptive mesh refinement

**State variables included**:
- Material concentrations (ablator, chamber gas, marker, foam)
- Mass density
- Laser energy deposition
- Pressure
- Electron and ion temperatures

**Keywords**: NIF, fusion, 3d, simulation

**DSI Database**: `nif.db`

Would you like me to load this dataset for further analysis?

Tools called: ['query_dsi_tool'] | 6.4s | 3737 tokens
DSI API calls: ['__init__', 'query', 'close']
[PASS] anthropic.claude-sonnet-4-5-20250929-v1:0 | L1_search_implosion — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_34

### `L1_download_nif_sim` — Level 1 / Data Preparation

**Query:** Download the simulation data for sim name: nifcylxyz_hdf5_plt_cnt_0000.flash

Successfully downloaded the simulation data file **nifcylxyz_hdf5_plt_cnt_0000.flash** to:
`/Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_34/nifcylxyz_hdf5_plt_cnt_0000.flash`

This is an HDF5 file from a 3D FLASH computation of a National Ignition Facility cylindrical implosion experiment (shot N210201-001) at timestep 0 (0 ns). The file contains state variables including ablator concentration, chamber material, marker material, foam, density, energy deposition, pressure, and electron/ion temperatures.

Tools called: ['query_dsi_tool', 'query_dsi_tool', 'load_dsi_tool', 'query_dsi_tool', 'query_dsi_tool', 'download_file_tool', 'download_file_tool'] | 20.9s | 5082 tokens
DSI API calls: ['__init__', 'query', 'close', '__init__', 'query', 'close', '__init__', 'list', 'close', '__init__', 'list', 'close', '__init__', 'list', 'schema', 'close', '__init__', 'query', 'close', '__init__', 'query', 'close']
[PASS] anthropic.claude-sonnet-4-5-20250929-v1:0 | L1_download_nif_sim — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_35

### `L1_store_poisson_hdf5` — Level 1 / Data Preparation

**Query:** Download this simulation data file: https://oceans11.lanl.gov/electrostaticEquations/LA-UR-25-29606-electrostatic_dataset_1k/data/electrostatic_poisson_32x32_1-1000.hdf5

The simulation data file has been successfully downloaded to:
`/Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_35/electrostatic_poisson_32x32_1-1000.hdf5`

Tools called: ['download_file_tool', 'download_file_tool'] | 7.1s | 3419 tokens
DSI API calls: []
[PASS] anthropic.claude-sonnet-4-5-20250929-v1:0 | L1_store_poisson_hdf5 — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_35

### `L1_owner_field` — Level 1 / Metadata Query

**Query:** Who is the owner of the NIF dataset"

Found it! The NIF dataset is titled "3D FLASH Computation of National Ignition Facility Shot".

**Owner of the NIF dataset:**
- **Contact Point:** Joshua Paul Sauppe
- **Email:** jpsauppe@lanl.gov

Tools called: ['query_dsi_tool', 'query_dsi_tool', 'query_dsi_tool'] | 9.6s | 3712 tokens
DSI API calls: ['__init__', 'query', 'close', '__init__', 'query', 'close', '__init__', 'query', 'close']
[PASS] anthropic.claude-sonnet-4-5-20250929-v1:0 | L1_owner_field — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_35

### `L1_extract_dataset_count` — Level 1 / Data Query

**Query:** How many datasets are in the Ocean 11 catalog?

There are **9 datasets** in the Ocean 11 catalog.

Tools called: ['query_dsi_tool'] | 4.1s | 2972 tokens
DSI API calls: ['__init__', 'query', 'close']
[PASS] anthropic.claude-sonnet-4-5-20250929-v1:0 | L1_extract_dataset_count — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_35

### `L1_extract_originating_org` — Level 1 / Metadata Query

**Query:** What organization is listed for the Ocean 11 datasets?

The organization listed for the Ocean 11 datasets is **DOE:LANL** (Department of Energy: Los Alamos National Laboratory).

Tools called: ['query_dsi_tool'] | 4.6s | 2994 tokens
DSI API calls: ['__init__', 'query', 'close']
[PASS] anthropic.claude-sonnet-4-5-20250929-v1:0 | L1_extract_originating_org — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_35

### `L1_extract_physics_theme_count` — Level 1 / Data Query

**Query:** How many datasets are categorized as physics?

There are **5 datasets** categorized as physics in the Ocean 11 dataset.

Tools called: ['query_dsi_tool'] | 4.3s | 3002 tokens
DSI API calls: ['__init__', 'query', 'close']
[PASS] anthropic.claude-sonnet-4-5-20250929-v1:0 | L1_extract_physics_theme_count — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_35

### `L1_nif_domain_extent` — Level 1 / Data Query

**Query:** What are the spatial bounds of the NIF simulation's computational domain?

Perfect! I found the NIF simulation dataset. According to the description, the spatial bounds of the computational domain are:

**Spatial Bounds:**
- **x-axis:** -3.072 mm to 3.072 mm
- **y-axis:** -3.072 mm to 3.072 mm
- **z-axis:** -3.072 mm to 3.072 mm

The computational domain is a **cubic domain** with dimensions of 6.144 mm × 6.144 mm × 6.144 mm, centered at the origin. The simulation uses adaptive mesh refinement with a minimum cell size of 8 microns.

Tools called: ['query_dsi_tool'] | 5.5s | 3769 tokens
DSI API calls: ['__init__', 'query', 'close']
[PASS] anthropic.claude-sonnet-4-5-20250929-v1:0 | L1_nif_domain_extent — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_35

### `L1_nif_timestep_count` — Level 1 / Data Query

**Query:** How many discrete timesteps of the NIF simulation are recorded in NIF.

The NIF simulation has **20 discrete timesteps** recorded in the database.

Tools called: ['query_dsi_tool', 'query_dsi_tool', 'query_dsi_tool', 'query_dsi_tool', 'load_dsi_tool', 'query_dsi_tool'] | 16.4s | 6137 tokens
DSI API calls: ['__init__', 'query', 'close', '__init__', 'query', 'close', '__init__', 'query', 'close', '__init__', 'query', 'close', '__init__', 'list', 'close', '__init__', 'list', 'close', '__init__', 'list', 'schema', 'close', '__init__', 'query', 'close']
[PASS] anthropic.claude-sonnet-4-5-20250929-v1:0 | L1_nif_timestep_count — score=1.0

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_36

### `L1_nif_array_field_count` — Level 1 / Data Query

**Query:** How many distinct physical quantity arrays are recorded per simulation timestep in NIF.

**9 distinct physical quantity arrays** are recorded per simulation timestep in the NIF dataset.

These arrays are:
1. **ablt** - concentration of ablator material (plastic, CH)
2. **cham** - concentration of background chamber material (helium)
3. **dens** - mass density [g/cm³]
4. **depo** - instantaneous energy per unit mass [erg/g] deposited by laser drive
5. **foam** - concentration of central foam (plastic, CH)
6. **mark** - concentration of marker material (aluminum)
7. **pres** - material pressure [erg/cm³]
8. **tele** - electron temperature [K]
9. **tion** - ion temperature [K]

Tools called: ['query_dsi_tool', 'query_dsi_tool', 'query_dsi_tool', 'query_dsi_tool', 'query_dsi_tool', 'query_dsi_tool', 'query_dsi_tool', 'load_dsi_tool', 'query_dsi_tool', 'query_dsi_tool'] | 27.0s | 7203 tokens
DSI API calls: ['__init__', 'query', 'close', '__init__', 'query', 'close', '__init__', 'query', 'close', '__init__', 'query', 'close', '__init__', 'query', 'close', '__init__', 'query', 'close', '__init__', 'query', 'close', '__init__', 'list', 'close', '__init__', 'list', 'close', '__init__', 'list', 'schema', 'close', '__init__', 'query', 'close', '__init__', 'query', 'close']
[PASS] anthropic.claude-sonnet-4-5-20250929-v1:0 | L1_nif_array_field_count — score=1.0

Saved: /Users/hhn/lanl/dsi/tools/ai_search/levels_benchmark_results/20260805_193326_level1_atomic__anthropic.claude-sonnet-4-5-20250929-v1_0.json
Saved: /Users/hhn/lanl/dsi/tools/ai_search/levels_benchmark_results/20260805_193326_level1_atomic__all_models.json

,model,task_id,level,category,passed,score,elapsed_sec,tokens,tools,notes,judge_efficiency_score,judge_efficiency_reasoning
0,aws-gov.gpt-5.4,L1_load_ocean11,1,Data Discovery,True,1.0,3.2,2292,load_dsi_tool,,0.10,"The reference needed a single read command, bu..."
1,aws-gov.gpt-5.4,L1_load_nif_direct,1,Data Discovery,True,1.0,2.6,1922,load_dsi_tool,,0.18,"The reference required a single read command, ..."
2,aws-gov.gpt-5.4,L1_load_poisson,1,Data Discovery,True,1.0,2.9,2016,load_dsi_tool,,0.20,The agent ultimately loaded the correct databa...
3,aws-gov.gpt-5.4,L1_search_implosion,1,Search,True,1.0,3.9,2376,query_dsi_tool,,0.60,The agent completed the task in a single query...
4,aws-gov.gpt-5.4,L1_download_nif_sim,1,Data Preparation,False,0.0,3.7,1838,query_dsi_tool,"Expected one of ['download_file_tool'], got ['...",0.10,"The agent made only one query, but it was agai..."
5,aws-gov.gpt-5.4,L1_store_poisson_hdf5,1,Data Preparation,True,1.0,2.9,1933,download_file_tool,,0.95,The agent completed the download in a single d...
6,aws-gov.gpt-5.4,L1_owner_field,1,Metadata Query,False,0.0,3.5,1791,query_dsi_tool,"Response missing keywords: ['Joshua', 'Paul', ...",0.90,The agent used a single targeted query with th...
7,aws-gov.gpt-5.4,L1_extract_dataset_count,1,Data Query,True,1.0,3.1,1748,query_dsi_tool,,1.00,The agent performed the equivalent minimal two...
8,aws-gov.gpt-5.4,L1_extract_originating_org,1,Metadata Query,True,1.0,2.0,1776,query_dsi_tool,,0.95,The agent effectively matched the optimal two-...
9,aws-gov.gpt-5.4,L1_extract_physics_theme_count,1,Data Query,True,1.0,2.0,1753,query_dsi_tool,,1.00,The agent executed a single direct count query...
10,aws-gov.gpt-5.4,L1_nif_domain_extent,1,Data Query,True,1.0,3.4,2405,query_dsi_tool,,0.35,The agent used a single query after opening th...
11,aws-gov.gpt-5.4,L1_nif_timestep_count,1,Data Query,False,0.0,4.5,3604,"query_dsi_tool, query_dsi_tool",Expected count 20 not found in tool results/re...,0.00,The agent never accessed the correct NIF datab...
12,aws-gov.gpt-5.4,L1_nif_array_field_count,1,Data Query,True,1.0,4.4,2652,"query_dsi_tool, load_dsi_tool, query_dsi_tool",,0.28,The agent found the answer but was much less e...
13,anthropic.claude-sonnet-4-5-20250929-v1:0,L1_load_ocean11,1,Data Discovery,True,1.0,5.0,3632,load_dsi_tool,,0.15,"The reference required a single read command, ..."
14,anthropic.claude-sonnet-4-5-20250929-v1:0,L1_load_nif_direct,1,Data Discovery,True,1.0,4.8,3252,load_dsi_tool,,0.15,"The reference needed a single read command, bu..."
15,anthropic.claude-sonnet-4-5-20250929-v1:0,L1_load_poisson,1,Data Discovery,True,1.0,5.4,3359,load_dsi_tool,,0.20,"The optimal path is a single read command, but..."
16,anthropic.claude-sonnet-4-5-20250929-v1:0,L1_search_implosion,1,Search,True,1.0,6.4,3737,query_dsi_tool,,0.55,The agent completed the task in a single query...
17,anthropic.claude-sonnet-4-5-20250929-v1:0,L1_download_nif_sim,1,Data Preparation,True,1.0,20.9,5082,"query_dsi_tool, query_dsi_tool, load_dsi_tool,...",,0.33,The agent reached the correct file but was muc...
18,anthropic.claude-sonnet-4-5-20250929-v1:0,L1_store_poisson_hdf5,1,Data Preparation,True,1.0,7.1,3419,"download_file_tool, download_file_tool",,0.15,The agent used two redundant download attempts...
19,anthropic.claude-sonnet-4-5-20250929-v1:0,L1_owner_field,1,Metadata Query,True,1.0,9.6,3712,"query_dsi_tool, query_dsi_tool, query_dsi_tool",,0.20,The agent used three separate database session...
20,anthropic.claude-sonnet-4-5-20250929-v1:0,L1_extract_dataset_count,1,Data Query,True,1.0,4.1,2972,query_dsi_tool,,1.00,The agent executed a single direct count query...
21,anthropic.claude-sonnet-4-5-20250929-v1:0,L1_extract_originating_org,1,Metadata Query,True,1.0,4.6,2994,query_dsi_tool,,1.00,The agent issued exactly the essential databas...
22,anthropic.claude-sonnet-4-5-20250929-v1:0,L1_extract_physics_theme_count,1,Data Query,True,1.0,4.3,3002,query_dsi_tool,,0.95,The agent used a single query against the corr...
23,anthropic.claude-sonnet-4-5-20250929-v1:0,L1_nif_domain_extent,1,Data Query,True,1.0,5.5,3769,query_dsi_tool,,0.30,The agent used a broader SQL search for 'NIF' ...
24,anthropic.claude-sonnet-4-5-20250929-v1:0,L1_nif_timestep_count,1,Data Query,True,1.0,16.4,6137,"query_dsi_tool, query_dsi_tool, query_dsi_tool...",,0.17,The agent eventually issued the correct final ...
25,anthropic.claude-sonnet-4-5-20250929-v1:0,L1_nif_array_field_count,1,Data Query,True,1.0,27.0,7203,"query_dsi_tool, query_dsi_tool, query_dsi_tool...",,0.14,The agent eventually used the right NIF table ...

### Model Comparison

Pass rate, score, latency, and token usage per model — use this to compare `POSSIBLE_MODELS` head-to-head on the same task set.

In [10]:
display(Markdown("### Overall summary by model"))
if "judge_efficiency_score" not in l1_df.columns:
    l1_df["judge_efficiency_score"] = float("nan")  # older results predating score_efficiency
model_summary = (
    l1_df.groupby("model")
    .agg(
        pass_rate=("passed", "mean"),
        avg_score=("score", "mean"),
        avg_efficiency=("judge_efficiency_score", "mean"),
        avg_tokens=("tokens", "mean"),
        avg_elapsed_sec=("elapsed_sec", "mean"),
        n_tasks=("task_id", "count"),
    )
    .round(2)
    .sort_values("pass_rate", ascending=False)
)
display(model_summary)

display(Markdown("### Pass rate by model and category"))
category_pivot = l1_df.pivot_table(index="model", columns="category", values="passed", aggfunc="mean").round(2)
display(category_pivot)

display(Markdown("### Pass/fail matrix by task and model"))
task_pivot = l1_df.pivot_table(index="task_id", columns="model", values="passed", aggfunc="first")
display(task_pivot)

### Overall summary by model

,pass_rate,avg_score,avg_efficiency,avg_tokens,avg_elapsed_sec,n_tasks
model,,,,,,
anthropic.claude-sonnet-4-5-20250929-v1:0,1.00,1.00,0.41,4020.77,9.32,13
aws-gov.gpt-5.4,0.77,0.77,0.51,2162.00,3.24,13

### Pass rate by model and category

category,Data Discovery,Data Preparation,Data Query,Metadata Query,Search
model,,,,,
anthropic.claude-sonnet-4-5-20250929-v1:0,1.0,1.0,1.0,1.0,1.0
aws-gov.gpt-5.4,1.0,0.5,0.8,0.5,1.0

### Pass/fail matrix by task and model

model,anthropic.claude-sonnet-4-5-20250929-v1:0,aws-gov.gpt-5.4
task_id,,
L1_download_nif_sim,True,False
L1_extract_dataset_count,True,True
L1_extract_originating_org,True,True
L1_extract_physics_theme_count,True,True
L1_load_nif_direct,True,True
L1_load_ocean11,True,True
L1_load_poisson,True,True
L1_nif_array_field_count,True,True
L1_nif_domain_extent,True,True
L1_nif_timestep_count,True,False
L1_owner_field,True,False
L1_search_implosion,True,True
L1_store_poisson_hdf5,True,True

### Level 2 — Workflow

In [11]:
# l2_results = run_level("level2_workflow", LEVEL2_TASKS)
# l2_df = results_to_dataframe(l2_results)
# display(l2_df)

### Level 3 — Discovery

In [12]:
# l3_results = run_level("level3_discovery", LEVEL3_TASKS)
# l3_df = results_to_dataframe(l3_results)
# display(l3_df)

## All Results

In [13]:
# all_results = l1_results 
# # + l2_results + l3_results
# summary_df = results_to_dataframe(all_results)

# display(Markdown("### Pass rate by level and category"))
# pivot = summary_df.pivot_table(
#     index="category", columns="level", values="passed", aggfunc="mean"
# ).round(2)
# display(pivot)

# display(Markdown("### Mean score by level and category"))
# score_pivot = summary_df.pivot_table(
#     index="category", columns="level", values="score", aggfunc="mean"
# ).round(2)
# display(score_pivot)

# display(Markdown("### Full results"))
# display(summary_df)

# save_results(all_results, "all_levels_summary")

## Single-Task Runner

This cell debugs individual tasks or add custom queries.

In [14]:
def debug_task(task_id: str, model_name: Optional[str] = None):
    """Run and score a single task by ID for interactive debugging.

    Looks up the task in ALL_TASKS, creates a fresh explorer, and prints pass/score.
    Pass model_name (any entry from POSSIBLE_MODELS) to debug that task against a
    specific model instead of the global default LLM_MODEL.
    """
    task = next(t for t in ALL_TASKS if t.task_id == task_id)
    explorer = make_explorer(llm=make_llm(model_name) if model_name else None)
    print(f"Agent workspace: {explorer.wrsk_path}")
    try:
        tr = run_task(explorer, task)
        tr = score_task(task, tr)
    except TaskTimeoutError as e:
        print(f"[TIMEOUT] {e}")
        tr = TaskResult(
            task_id=task.task_id, level=task.level, category=task.category, query=task.query,
            response="", tool_calls=[], elapsed_sec=task.timeout_sec or TASK_TIMEOUT_SEC, tokens=0,
            passed=False, score=0.0, notes=f"timeout: {e}",
        )
    tr.model = model_name or LLM_MODEL
    print(f"Model: {tr.model}")
    print(f"Passed: {tr.passed} | Score: {tr.score}")
    print(f"Tools: {tr.tool_calls}")
    print(f"DSI API calls:\n{format_dsi_call_log(tr.dsi_calls)}")
    if tr.notes:
        print(f"Notes: {tr.notes}")
    if tr.judge_scores:
        print(json.dumps(tr.judge_scores, indent=2))
    return tr

# Example: debug_task("L1_load_ocean11", model_name="anthropic.claude-sonnet-4-5-20250929-v1:0")

In [15]:
# Run task 1 and display its agent logs
task = LEVEL1_TASKS[0]
explorer = make_explorer()
tr = run_task(explorer, task)
tr = score_task(task, tr)

print(f"Passed: {tr.passed} | Score: {tr.score}")
print(f"DSI API calls:\n{format_dsi_call_log(tr.dsi_calls)}")
print(Path(explorer.wrsk_path, "run.log").read_text())

Creating workspace at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_36

### `L1_load_ocean11` — Level 1 / Data Discovery

**Query:** Load the ocean_11_datasets.db database.

Loaded `/Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/ocean_11_datasets.db`.

Tools called: ['load_dsi_tool'] | 2.1s | 2292 tokens
DSI API calls: ['__init__', 'list', 'close', '__init__', 'list', 'close', '__init__', 'list', 'schema', 'close']
Passed: True | Score: 1.0
DSI API calls:
[1] DSI.__init__('/Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/ocean_11_datasets.db', check_same_thread=False)  [0.003s]
[2] DSI.list(True)  [0.000s]
[3] DSI.close()  [0.000s]
[4] DSI.__init__('/Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/ocean_11_datasets.db', check_same_thread=False)  [0.003s]
[5] DSI.list(True)  [0.000s]
[6] DSI.close()  [0.000s]
[7] DSI.__init__('/Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/ocean_11_datasets.db', check_same_thread=False)  [0.002s]
[8] DSI.list(True)  [0.000s]
[9] DSI.schema()  [0.001s]
[10] DSI.close()  [0.000s]
2026-08-05 19:36:43,190 [INFO] global_logger: !!!!!
!!!!!Starting DSIExplorer agent initialization.
2026-08-05 19:36:43,190 [INFO] global_logger: Workspace created at: /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_36
2026-08-05 19:36:43,190 [INFO] global_logger: Checkpoint database created with thread id: 4536
2026-08-05 19:36:43,190 [DEBUG] global_logger: master_db_folder: /Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/
2026-08-05 19:36:43,198 [DEBUG] global_logger: master_database_path: /Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/ocean_11_datasets.db
2026-08-05 19:36:43,198 [DEBUG] global_logger: master_db_folder: /Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/
2026-08-05 19:36:43,198 [DEBUG] global_logger: Initialized DSIExplorerWorker with name: dsi_explorer_executor, prompt:
        You are a data-analysis agent who can write python code, SQL queries, and generate plots to answer user questions based on the data available in a DSI object.
        Use the load_dsi_tool tool to load DSI files that have a .db extension
        Use query_dsi_tool to run SQL queries on it
        When a user asks for data or dataset or ... you have, do NOT list the schema or metadata information you have about tables. Query the DSI objects for data and list the data in the tables.

        You can:
        - write and execute Python code,
        - compose SQL statements but ONLY select; no update or delete
        - generate plots and diagrams,
        - analyze and summarize data.

        Requirements:
        - Planning: Think carefully about the problem, but **do not show your reasoning**.
        - Data:
            - Always use the provided tools when available — never simulate results.
            - Never fabricate or assume sample data. Query or compute real values only.
            - When creating plots or files, always save them directly to disk (do not embed inline output).
            - Do not infer or assume any data beyond what is provided by the tools.
        - Keep all responses concise and focused on the requested task.
        - Only load a dataset when explicitly asked by a user
        - Do not restate the prompt or reasoning; just act and report the outcome briefly.
        - All downloaded files, generated plots, and outputs must be saved to  /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_36.
        , llm: bound=ChatOpenAI(metadata={'lc_versions': {'langchain-core': '1.4.8', 'langchain': '1.3.11', 'langchain-openai': '1.3.3'}}, client=<openai.resources.chat.completions.completions.Completions object at 0x346f85a90>, async_client=<openai.resources.chat.completions.completions.AsyncCompletions object at 0x346f86510>, root_client=<openai.OpenAI object at 0x345fe8ec0>, root_async_client=<openai.AsyncOpenAI object at 0x346f86270>, model_name='aws-gov.gpt-5.4', temperature=0.1, model_kwargs={}, openai_api_key=SecretStr('**********'), openai_api_base='https://aiportal-api.aws.lanl.gov', stream_chunk_timeout=120.0) kwargs={'tools': [{'type': 'function', 'function': {'name': 'query_dsi_tool', 'description': 'Execute a SQL query on a DSI object.', 'parameters': {'properties': {'query_str': {'description': 'the SQL query to run on DSI object', 'type': 'string'}, 'db_path': {'description': 'the absolute path to the DSI database to query', 'type': 'string'}}, 'required': ['query_str', 'db_path'], 'type': 'object'}}}, {'type': 'function', 'function': {'name': 'python_repl_tool', 'description': 'Executes arbitrary Python code. The executed code must save any plots or files to disk, not return them directly.', 'parameters': {'properties': {'code': {'description': 'Python code to execute. All generated outputs (plots, data, files) must be written to disk.', 'type': 'string'}}, 'required': ['code'], 'type': 'object'}}}, {'type': 'function', 'function': {'name': 'load_dsi_tool', 'description': 'Load a DSI object from the path and add information to the context for the llm to use.', 'parameters': {'properties': {'path': {'description': 'the path to the DSI object to load', 'type': 'string'}, 'run_path': {'default': '', 'description': 'the path this code is being run from', 'type': 'string'}, 'master_db_folder': {'default': '', 'description': 'the folder containing the master database, used to resolve relative paths when loading new databases', 'type': 'string'}}, 'required': ['path'], 'type': 'object'}}}, {'type': 'function', 'function': {'name': 'download_file_tool', 'description': 'Download a file from a URL and save it locally.', 'parameters': {'properties': {'url': {'description': 'a string containing the URL of the file to download.', 'type': 'string'}, 'output_path': {'default': '.', 'description': 'the local path where the file should be saved.', 'type': 'string'}}, 'required': ['url'], 'type': 'object'}}}, {'type': 'function', 'function': {'name': 'arxiv_search_tool', 'description': 'Search arXiv.org for research papers related to a given topic.', 'parameters': {'properties': {'query': {'description': 'Topic or keywords to search for.', 'type': 'string'}, 'max_results': {'default': 10, 'description': 'How many papers to return (default 5).', 'type': 'integer'}}, 'required': ['query'], 'type': 'object'}}}, {'type': 'function', 'function': {'name': 'wikipedia_search_tool', 'description': 'Search Wikipedia for information about the search query.', 'parameters': {'properties': {'query': {'description': 'Search query or topic.', 'type': 'string'}, 'max_results': {'default': 5, 'description': 'Max number of results from each source.', 'type': 'integer'}}, 'required': ['query'], 'type': 'object'}}}, {'type': 'function', 'function': {'name': 'web_search_tool', 'description': 'Perform a web search and return structured results.', 'parameters': {'properties': {'query': {'description': 'Search query', 'type': 'string'}, 'max_results': {'default': 5, 'description': 'Max number of results to return', 'type': 'integer'}}, 'required': ['query'], 'type': 'object'}}}, {'type': 'function', 'function': {'name': 'send_email_tool', 'description': 'Send an email using SMTP.', 'parameters': {'properties': {'recipient': {'description': 'The destination email address.', 'type': 'string'}, 'subject': {'description': 'The subject line of the email.', 'type': 'string'}, 'body': {'description': 'The plain-text body of the email.', 'type': 'string'}, 'smtp_host': {'default': 'smtp.example.com', 'description': 'The SMTP server hostname. Defaults to "smtp.example.com".', 'type': 'string'}, 'smtp_port': {'default': 587, 'description': 'The SMTP server port (typically 587 for TLS, 465 for SSL). Defaults to 587.', 'type': 'integer'}, 'username': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'default': None, 'description': 'SMTP authentication username, or None if not required.'}, 'password': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'default': None, 'description': 'SMTP authentication password, or None if not required.'}}, 'required': ['recipient', 'subject', 'body'], 'type': 'object'}}}, {'type': 'function', 'function': {'name': 'upload_paper_tool', 'description': 'Upload a local PDF to OpenAI Files API and return identifiers.', 'parameters': {'properties': {'path': {'description': 'the path of the DSI object to load', 'type': 'string'}}, 'required': ['path'], 'type': 'object'}}}]} config={} config_factories=[]
2026-08-05 19:36:43,198 [INFO] global_logger: Worker agent created.
2026-08-05 19:36:43,198 [DEBUG] global_logger: Worker prompt:
        You are a data-analysis agent who can write python code, SQL queries, and generate plots to answer user questions based on the data available in a DSI object.
        Use the load_dsi_tool tool to load DSI files that have a .db extension
        Use query_dsi_tool to run SQL queries on it
        When a user asks for data or dataset or ... you have, do NOT list the schema or metadata information you have about tables. Query the DSI objects for data and list the data in the tables.

        You can:
        - write and execute Python code,
        - compose SQL statements but ONLY select; no update or delete
        - generate plots and diagrams,
        - analyze and summarize data.

        Requirements:
        - Planning: Think carefully about the problem, but **do not show your reasoning**.
        - Data:
            - Always use the provided tools when available — never simulate results.
            - Never fabricate or assume sample data. Query or compute real values only.
            - When creating plots or files, always save them directly to disk (do not embed inline output).
            - Do not infer or assume any data beyond what is provided by the tools.
        - Keep all responses concise and focused on the requested task.
        - Only load a dataset when explicitly asked by a user
        - Do not restate the prompt or reasoning; just act and report the outcome briefly.
        - All downloaded files, generated plots, and outputs must be saved to  /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_36.

2026-08-05 19:36:43,200 [INFO] global_logger: Tool node created.
2026-08-05 19:36:43,201 [INFO] global_logger: Graph compiled.
2026-08-05 19:36:43,201 [INFO] global_logger: DSI Explorer agent initialization complete.
2026-08-05 19:36:43,205 [DEBUG] global_logger:

DSIExplorerWorker.__call__ :: 'dsi_explorer_executor' ai invoked with: You are a data-analysis agent who can write python code, SQL queries, and generate plots to answer user questions based on the data available in a DSI object.
        Use the load_dsi_tool tool to load DSI files that have a .db extension
        Use query_dsi_tool to run SQL queries on it
        When a user asks for data or dataset or ... you have, do NOT list the schema or metadata information you have about tables. Query the DSI objects for data and list the data in the tables.

        You can:
        - write and execute Python code,
        - compose SQL statements but ONLY select; no update or delete
        - generate plots and diagrams,
        - analyze and summarize data.

        Requirements:
        - Planning: Think carefully about the problem, but **do not show your reasoning**.
        - Data:
            - Always use the provided tools when available — never simulate results.
            - Never fabricate or assume sample data. Query or compute real values only.
            - When creating plots or files, always save them directly to disk (do not embed inline output).
            - Do not infer or assume any data beyond what is provided by the tools.
        - Keep all responses concise and focused on the requested task.
        - Only load a dataset when explicitly asked by a user
        - Do not restate the prompt or reasoning; just act and report the outcome briefly.
        - All downloaded files, generated plots, and outputs must be saved to  /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_36.

The following phrases all refer to this same database:
            - "master database"
            - "master dataset"
            - "DSIExplorer master database"
            - "Diana dataset

            When the user asks to reload, refresh, reset, reinitialize, restart, or
            the **master database**, interpret that as a request to reload the
            DSIExplorer master database at /Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/ocean_11_datasets.db using the tool load_dsi_tool.
            Do no reload or load the master dataset unless explicitly asked by the user.

            The the path this code is being run from (run_path) is /Users/hhn/lanl/dsi/tools/ai_search


The current working database path (current_db_abs_path) is: /Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/ocean_11_datasets.db

The master database path (master_database_path) is: /Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/ocean_11_datasets.db

The schema of the dataset loaded: CREATE TABLE genesis_datacard (Title VARCHAR, "Keywords/Tag" VARCHAR, "Update/Modification_Date" VARCHAR, "Theme/Category_:_Domain" VARCHAR, Description_ VARCHAR, Contact_Point_ VARCHAR, "Formatted_Name*Format_with_separate_fields_for_first,_last_and_optional_middle" VARCHAR, Email VARCHAR, "Access_Rights_:_SecurityClassification_(Information_Sensitivity?)" VARCHAR, CUI_Restriction VARCHAR, CUI_Banner_Marking VARCHAR, CUI_Designatin_Indicator VARCHAR, Originating_Organization VARCHAR, dsi_database TEXT)

Dataset description: Field_glossary for DSI dataset: ocean_11_datasets

Table: genesis_datacards
  desc: Contains data about the resources available in the Ocean 11 dataset.
Fields:
  Title:
    desc: Short human-readable name of the resource.

  Keywords:
    desc: Tags/keywords describing the content.

  Update/Modification_Date:
    desc: Last modification date.

  Theme/Category_:_Domain:
    desc: High-level domain or thematic category.

  Description_:
    desc: One-sentence summary of the resource.

  Contact_Point_:
    desc: Primary individual or group who own this dataset and can be contacted.

  Formatted_Name:
    desc: Structured contact name fields. e.g. { first: "Jane", middle: "A.", last: "Smith" }

  Email:
    desc: Contact email.

  Access_Rights:
    desc: Security or access classification.

  CUI_Restriction:
    desc: CUI status and restriction category.

  CUI_Banner_Marking:
    desc: Banner marking required for CUI data.

  CUI_Designation_Indicator:
    desc: Specific CUI category indicator.

  Originating_Organization:
    desc: Organization or project that produced the resource.

  dsi_database:
    desc: Path for associated DSI database that can be loaded. Use this path when asked to load/read in the dataset using the DSI tool.

Load the ocean_11_datasets.db database.

2026-08-05 19:36:44,361 [DEBUG] global_logger:

DSIExplorerWorker.__call__ :: 'dsi_explorer_executor' ai invoked with: You are a data-analysis agent who can write python code, SQL queries, and generate plots to answer user questions based on the data available in a DSI object.
        Use the load_dsi_tool tool to load DSI files that have a .db extension
        Use query_dsi_tool to run SQL queries on it
        When a user asks for data or dataset or ... you have, do NOT list the schema or metadata information you have about tables. Query the DSI objects for data and list the data in the tables.

        You can:
        - write and execute Python code,
        - compose SQL statements but ONLY select; no update or delete
        - generate plots and diagrams,
        - analyze and summarize data.

        Requirements:
        - Planning: Think carefully about the problem, but **do not show your reasoning**.
        - Data:
            - Always use the provided tools when available — never simulate results.
            - Never fabricate or assume sample data. Query or compute real values only.
            - When creating plots or files, always save them directly to disk (do not embed inline output).
            - Do not infer or assume any data beyond what is provided by the tools.
        - Keep all responses concise and focused on the requested task.
        - Only load a dataset when explicitly asked by a user
        - Do not restate the prompt or reasoning; just act and report the outcome briefly.
        - All downloaded files, generated plots, and outputs must be saved to  /Users/hhn/lanl/dsi/tools/ai_search/dsi_explorer_agent__2026_08_05__19_36.

The following phrases all refer to this same database:
            - "master database"
            - "master dataset"
            - "DSIExplorer master database"
            - "Diana dataset

            When the user asks to reload, refresh, reset, reinitialize, restart, or
            the **master database**, interpret that as a request to reload the
            DSIExplorer master database at /Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/ocean_11_datasets.db using the tool load_dsi_tool.
            Do no reload or load the master dataset unless explicitly asked by the user.

            The the path this code is being run from (run_path) is /Users/hhn/lanl/dsi/tools/ai_search


The current working database path (current_db_abs_path) is: /Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/ocean_11_datasets.db

The master database path (master_database_path) is: /Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/ocean_11_datasets.db

The schema of the dataset loaded: CREATE TABLE genesis_datacard (Title VARCHAR, "Keywords/Tag" VARCHAR, "Update/Modification_Date" VARCHAR, "Theme/Category_:_Domain" VARCHAR, Description_ VARCHAR, Contact_Point_ VARCHAR, "Formatted_Name*Format_with_separate_fields_for_first,_last_and_optional_middle" VARCHAR, Email VARCHAR, "Access_Rights_:_SecurityClassification_(Information_Sensitivity?)" VARCHAR, CUI_Restriction VARCHAR, CUI_Banner_Marking VARCHAR, CUI_Designatin_Indicator VARCHAR, Originating_Organization VARCHAR, dsi_database TEXT)

Dataset description: Field_glossary for DSI dataset: ocean_11_datasets

Table: genesis_datacards
  desc: Contains data about the resources available in the Ocean 11 dataset.
Fields:
  Title:
    desc: Short human-readable name of the resource.

  Keywords:
    desc: Tags/keywords describing the content.

  Update/Modification_Date:
    desc: Last modification date.

  Theme/Category_:_Domain:
    desc: High-level domain or thematic category.

  Description_:
    desc: One-sentence summary of the resource.

  Contact_Point_:
    desc: Primary individual or group who own this dataset and can be contacted.

  Formatted_Name:
    desc: Structured contact name fields. e.g. { first: "Jane", middle: "A.", last: "Smith" }

  Email:
    desc: Contact email.

  Access_Rights:
    desc: Security or access classification.

  CUI_Restriction:
    desc: CUI status and restriction category.

  CUI_Banner_Marking:
    desc: Banner marking required for CUI data.

  CUI_Designation_Indicator:
    desc: Specific CUI category indicator.

  Originating_Organization:
    desc: Organization or project that produced the resource.

  dsi_database:
    desc: Path for associated DSI database that can be loaded. Use this path when asked to load/read in the dataset using the DSI tool.

Load the ocean_11_datasets.db database.



{"the current working database path (current_db_abs_path) is": "/Users/hhn/lanl/dsi/tools/ai_search/data/oceans_11/ocean_11_datasets.db", "the current databse schema is": "CREATE TABLE genesis_datacard (Title VARCHAR, \"Keywords/Tag\" VARCHAR, \"Update/Modification_Date\" VARCHAR, \"Theme/Category_:_Domain\" VARCHAR, Description_ VARCHAR, Contact_Point_ VARCHAR, \"Formatted_Name*Format_with_separate_fields_for_first,_last_and_optional_middle\" VARCHAR, Email VARCHAR, \"Access_Rights_:_SecurityClassification_(Information_Sensitivity?)\" VARCHAR, CUI_Restriction VARCHAR, CUI_Banner_Marking VARCHAR, CUI_Designatin_Indicator VARCHAR, Originating_Organization VARCHAR, dsi_database TEXT)", "the database description is": "Field_glossary for DSI dataset: ocean_11_datasets

Table: genesis_datacards
  desc: Contains data about the resources available in the Ocean 11 dataset.
Fields:
  Title:

## MCP Mode

To benchmark via MCP (atomic tools on `levels_mcp_server.py`):

1. In a terminal: `python levels_mcp_server.py`
2. Set `USE_MCP = True` in the config cell and re-run setup.

Inspector: `npx @modelcontextprotocol/inspector` → Streamable HTTP → `http://127.0.0.1:8000/mcp`