# Federation Demo  
In this demo, you will be shown:  
- how to see the datasets imported
- how to search for data
- merge data from different tables
- add a table to an existing database

Some Imports

In [1]:
from dsi.dsi import DSI
from dsi.dsifederated import DSIFederated

Help for DSI and Federated DSI

In [2]:
help(DSI)

Help on class DSI in module dsi.dsi:

class DSI(builtins.object)
 |  DSI(filename='.temp_dsi.db', backend_name='Sqlite', **kwargs)
 |
 |  A user-facing interface for DSI's Core middleware.
 |
 |  The DSI Class abstracts Core.Terminal for managing metadata and Core.Sync for data management and movement.
 |
 |  Methods defined here:
 |
 |  __init__(self, filename='.temp_dsi.db', backend_name='Sqlite', **kwargs)
 |      Initializes DSI by activating a backend for data operations; default is a Sqlite backend for temporary data analysis.
 |      If users specify `filename`, data is saved to a permanent backend file.
 |
 |      `filename` : str, optional, default is ".temp_dsi.db"
 |          If not specified, a temporary, hidden backend file is created for users to analyze their data.
 |          If specified and backend file already exists, it is activated for a user to explore its data.
 |          If specified and backend file does not exist, a file with this name is created.
 |
 |          Accepted file extensions for DSI-compatible backends:
 |              - If backend_name = "Sqlite" → .db, .sqlite, .sqlite3
 |              - If backend_name = "DuckDB" → .duckdb, .db
 |
 |      `backend_name` : str, optional, default is "Sqlite".
 |          Name of the backend to activate.
 |
 |          If using a DSI-supported backend, must be either "Sqlite", "DuckDB".
 |
 |          If using an external backend, provide the relative path to the Python module with the backend.
 |
 |  close(self)
 |      Closes the connection to the active backend and clears all loaded DSI modules.
 |
 |  display(self, table_name, num_rows=25, display_cols=None)
 |      Prints data from a specified table in the active backend.
 |
 |      `table_name` : str
 |          Name of the table to display.
 |
 |      `num_rows` : int, optional, default=25
 |          Maximum number of rows to print. If the table contains fewer rows, only those are shown.
 |
 |      `display_cols` : list of str, optional
 |          List of specific column names to display from the table.
 |
 |          If None (default), all columns are displayed.
 |
 |  fetch(self, fname)
 |
 |  find(self, query, collection=False, update=False)
 |      Finds all rows in the table where a column-level condition (e.g., "age > 4") is satisfied.
 |
 |      `query` : str
 |          A column-level condition that must be in the format of a [column name] [operator] [value].
 |          The value can be a string or number. Valid operators as example queries:
 |
 |          - age > 4
 |          - age < 4
 |          - age >= 4
 |          - age <= 4
 |          - age = 4
 |          - age == 4
 |          - age ~ 4    --> column age contains the number 4
 |          - age ~~ 4   --> column age contains the number 4
 |          - age != 4
 |          - age (4, 8) --> all values in 'age' between 4 and 8 (inclusive)
 |
 |      `collection` : bool, optional, default False.
 |          If True, returns a pandas DataFrame representing a subset of table rows that satisfy the `query`.
 |
 |          If False (default), prints the result.
 |
 |      `update` : bool, optional, default False.
 |          If True, includes 'dsi_table_name' and 'dsi_row_index' columns required for ``dsi.update()``.
 |
 |          If False (default), return object does not include these columns.
 |
 |      `return` : If there are no matches found, then nothing is returned or printed
 |
 |  get(self, dbname=None)
 |      #help, edge-finding (find this/that)
 |
 |  get_table(self, table_name, collection=False, update=False)
 |      Retrieves all data from a specified table without requiring knowledge of the active backend's query language.
 |
 |      This method offers a simplified alternative to `query()` for retrieving a full table data without using SQL.
 |
 |      `table_name` : str
 |          Name of the table from which all data will be retrieved.
 |
 |      `collection` : bool, optional, default False.
 |          If True, returns the result as a pandas DataFrame.
 |
 |          If False (default), prints the result.
 |
 |      `update` : bool, optional, default False.
 |          If True, includes a 'dsi_table_name' column required for ``dsi.update()``.
 |
 |          If False (default), return object does not include this column.
 |
 |      `return`: If `table_name` does not exist in the backend, then nothing is returned or printed
 |
 |  list(self, collection: bool = False) -> list | None
 |      Gets the names and dimensions (rows x columns) of all tables in the active backend.
 |
 |      Arguments:
 |          collection (bool): If True, returns a Python list of all the table names else if False (default), prints each table's name and dimensions to the console.
 |
 |      Returns:
 |          list | None : list of table names if collection is True, else None. If there are no tables in the backend, then nothing is returned or printed.
 |
 |      Raises:
 |          ValueError: If backend is empty or invalid.
 |          RuntimeError: If called before schema data is loaded or if listing fails.
 |
 |  list_backends(self)
 |      Prints a list of valid backends that can be used in the `backend_name` argument in `backend()`
 |
 |  list_readers(self)
 |      Prints a list of valid readers that can be used in the `reader_name` argument in `read()`
 |
 |  list_writers(self)
 |      Prints a list of valid writers that can be used in the `writer_name` argument in `write()`
 |
 |  move(self, filepath)
 |
 |  num_tables(self)
 |      Prints the number of tables in the active backend.
 |
 |  query(self, statement, collection=False, update=False)
 |      Executes a SQL query on the active backend.
 |
 |      `statement` : str
 |          A SQL query to execute. Only `SELECT` and `PRAGMA` statements are allowed.
 |
 |      `collection` : bool, optional, default False.
 |          If True, returns the result as a pandas DataFrame.
 |
 |          If False (default), prints the result.
 |
 |      `update` : bool, optional, default False.
 |          If True, includes a 'dsi_table_name' column required for ``dsi.update()``.
 |
 |          If False (default), return object does not include this column.
 |
 |      `return`: If the `statement` is incorrectly formatted, then nothing is returned or printed
 |
 |  read(self, data_sources: str | list[str] | dict | pandas.core.frame.DataFrame | None = None, reader_name: str | None = None, table_name=None, **kwargs)
 |      Loads data into DSI using the specified parameter `reader_name`
 |
 |      `data_sources` : str, list of str, or data object (dict or pandas DataFrame)
 |          File path(s) to the data, or an in-memory data object.
 |
 |          The expected input type depends on the selected `reader_name` (if a DSI-supported Reader):
 |              - "Collection"           → python dictionary, OrderedDict, or pandas DataFrame
 |              - "CSV"                  → .csv
 |              - "Parquet"              → .pq
 |              - "YAML"                 → .yaml or .yml
 |              - "YAML1"                → .yaml or .yml
 |              - "TOML"                 → .toml
 |              - "TOML1"                → .toml
 |              - "JSON"                 → .json
 |              - "Ensemble"             → .csv
 |              - "Cloverleaf"           → /path/to/data/directory/
 |              - "Bueno"                → .data
 |              - "DublinCoreDatacard"   → .xml
 |              - "SchemaOrgDatacard"    → .json
 |              - "GoogleDatacard"       → .yaml or .yml
 |              - "Oceans11Datacard"     → .yaml or .yml
 |              - "GenesisDatacard"      → .md
 |
 |      `reader_name` : str
 |          Name of the DSI Reader to use for loading the data.
 |
 |          If using a DSI-supported Reader, this should be one of the reader_names from `list_readers()`.
 |
 |          If using a custom Reader, provide the relative file path to the Python script with the Reader.
 |          For guidance on creating a DSI-compatible Reader, view :ref:`custom_reader`.
 |
 |      `table_name` : str, optional
 |          Name to assign to the loaded table.
 |
 |          Required when using the `Collection` reader to load an dictionary or pandas DataFrame representing only one table.
 |
 |          Recommended when the input file contains a single table for the `CSV`, `Parquet`, `JSON`, or `Ensemble` reader.
 |
 |  schema(self, filename=None)
 |      Either loads a relational database schema into DSI with a specified `filename` OR returns this database's structural schema.
 |
 |      `filename` : str, optional
 |          Path to a JSON file describing the relationships of the tables in a database.
 |          The schema should follow the format described in :ref:`user_schema_example_label`
 |
 |      `return` : If filename = None, returns the structural schema of this database - table/col names and their units.
 |      **If loading a relational schema, this function must be called before reading in any associated data files**
 |
 |  search(self, query, collection=False)
 |      Finds all rows across all tables in the active backend where `query` can be found.
 |
 |      `query` : int, float, or str
 |          The value to search for in all rows across all tables.
 |
 |      `collection` : bool, optional, default False.
 |          If True, returns a list of pandas DataFrames representing a subset of tables where `query` is found.
 |
 |          If False (default), prints the matches to the console.
 |
 |  summary(self, table_name=None, collection=False)
 |      Prints numerical metadata and (optionally) sample data from tables in the active backend.
 |
 |      `table_name` : str, optional
 |          If specified, only the numerical metadata for that table will be printed.
 |
 |          If None (default), metadata for all available tables is printed.
 |
 |      `collection` : bool, optional, default False.
 |          If True, and table_name specified, returns a Pandas DataFrame of the summary of that table.
 |
 |          If True, and table_name not specified, returns a list of Pandas DataFrames of the summary of all tables.
 |
 |          If False (default), prints each table's name and dimensions to the console.
 |
 |  update(self, collection, backup=False)
 |      Updates data in one or more tables in the active backend using the provided input.
 |      Intended to be used after modifying the output of `find()`, `search()`, `query()`, or `get_table()`
 |
 |      `collection` : pandas.DataFrame
 |          The data used to update a table.
 |          DataFrame must include unchanged **`dsi_`** columns from `find()`, `search()`, `query()` or `get_table()` to successfully update.
 |
 |          - If a `query()` DataFrame is the input, the corresponding table in the backend will be completely overwritten.
 |
 |      `backup` : bool, optional, default False.
 |          If True, creates a backup file for the DSI backend before updating its data.
 |
 |          If False (default), only updates the data.
 |
 |      - NOTE: Columns from the original table cannot be deleted during update. Only row edits or column additions are allowed.
 |      - NOTE: If update() affects a user-defined primary key column, row order may change upon reinsertion.
 |
 |  write(self, filename, writer_name, table_name=None, **kwargs)
 |      Exports data from the active backend using the specified `writer_name`.
 |
 |      `filename` : str
 |          Name of the output file to write.
 |
 |          Expected file extensions based on `writer_name` (if a DSI-supported Writer):
 |              - "ER_Diagram"   → .png, .pdf, .jpg, .jpeg
 |              - "Table_Plot"   → .png, .jpg, .jpeg
 |              - "Csv"          → .csv
 |              - "Parquet"      → .pq
 |
 |      `writer_name` : str
 |          Name of the DSI Writer to export data.
 |
 |          If using a DSI-supported Writer, this should be one of the writer_names from `list_writers()`.
 |
 |          If using a custom Writer, provide the relative file path to the Python script with the Writer.
 |          For guidance on creating a DSI-compatible Writer, view :ref:`custom_writer`.
 |
 |      `table_name`: str, optional
 |          Required when using "Table_Plot", "Csv" or "Parquet" to specify which table to export.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

In [3]:
help(DSIFederated)

Help on class DSIFederated in module dsi.dsifederated:

class DSIFederated(builtins.object)
 |  DSIFederated(federated_folder_path: str, operating_mode: str = 'console')
 |
 |  A class for federated querying of DSI databases. It loads metadata about the databases and
 |  their tables from a specified folder, and provides methods to summarize, query, search, and find data across the federated databases.
 |
 |  Methods defined here:
 |
 |  __init__(self, federated_folder_path: str, operating_mode: str = 'console')
 |      Initializes the DSIFederated class by loading metadata about the federated databases and their tables from a specified folder.
 |
 |      Args:
 |          federated_folder_path (str): The file path to the folder containing the metadata about the federated databases. The folder should contain a JSON file named "dsi_database_list.json" with the metadata information.
 |          operating_mode (str): console or notebook, determines how the results are displayed. Default is "console".
 |
 |  f_add_table(self, src_db_id: str, src_tbl_name: str, dst_db_id: str, dst_tbl_name: str | None = None, overwrite: bool = False) -> None
 |      Copy a table from one database into another database.
 |
 |      Args:
 |          src_db_id (str): Source database ID.
 |          src_tbl_name (str): Source table name.
 |          dst_db_id (str): Destination database ID.
 |          dst_tbl_name (str | None): Destination table name. If None, use src_tbl_name.
 |          overwrite (bool): If True, overwrite destination table if it exists.
 |
 |  f_federate(self, config_file: str, orkspace_folder: str = '')
 |      Federates databases based on a specified configuration file containing the criteria for federating the databases.
 |
 |      Args:
 |          config_path (str): The file path to the configuration file containing the criteria for federating the databases. The configuration file should be in JSON format and contain the necessary information for federating the databases.
 |
 |  f_find(self, query: str, db: str | None = None, table: str | None = None, original_location: str | None = None)
 |      Calls DSI Find in a database specified by db within the federated system.
 |          If no table and database are specified, queries all tables in the database.
 |
 |      Args:
 |          query (str): The query to find in the specified table.
 |          db (str | None): The name of the database containing the table. If None, this criterion is ignored. Default is None.
 |          table (str | None): The name of the table to find. If None, this criterion is ignored. Default is None.
 |          original_location (str | None): A string to search for in the original location of the databases. If None, this criterion is ignored. Default is None.
 |
 |      Returns:
 |          The result of the find operation.
 |
 |  f_get_db_path(self, db: str | None = None, table: str | None = None, original_location: str | None = None) -> list[str]
 |      Finds the file path of a database containing a specified table and database name within the federated system.
 |
 |      Args:
 |          table (str): The name of the table to find.
 |          db (str): The name of the database containing the table.
 |
 |      Returns:
 |          list[str]: The file path(s) of the database containing the specified table and database name.
 |
 |  f_list_databases(self, return_output: bool = False) -> list[dict] | None
 |      Prints a DataFrame containing information about the federated databases, including their paths, names, and tables.
 |
 |      Args:
 |          return_output (bool): Whether to return the output as a list of dictionaries. Default is False.
 |
 |      Returns:
 |          list[dict]: A list of dictionaries, where each dictionary contains information about a federated database, including its path, name, original location, and tables.
 |
 |  f_merge(self, src_db_id: str, src_tbl_name: str, dst_db_id: str, dst_tbl_name: str, mode: str = 'inner')
 |      Merge src table into dst table and overwrite the destination table.
 |
 |      Args:
 |          src_db_id (str): The ID of the source database containing the table to be merged.
 |          src_tbl_name (str): The name of the source table to be merged.
 |          dst_db_id (str): The ID of the destination database containing the table to merge into.
 |          dst_tbl_name (str): The name of the destination table to merge into.
 |          mode (str): How to handle column mismatches:
 |              - "inner": keep only shared columns
 |              - "outer": keep union of columns
 |              - "exact": require identical columns
 |
 |  f_query(self, query: str, db: str | None = None, table: str | None = None, original_location: str | None = None)
 |      DSI Query within the federated system.
 |          If no table and database are specified, queries all tables in the database.
 |
 |      Args:
 |          query (str): The query to execute on the specified table.
 |          db (str | None): The name of the database containing the table. If None, this criterion is ignored. Default is None.
 |          table (str | None): The name of the table to query. If None, this criterion is ignored. Default is None.
 |          original_location (str | None): A string to search for in the original location of the databases. If None, this criterion is ignored. Default is None.
 |
 |      Returns:
 |          The result of the query execution.
 |
 |  f_search(self, query: str, db: str | None = None, table: str | None = None, original_location: str | None = None)
 |      Calls DSI Search within a specified database within the federated system.
 |      If no table and database are specified, queries all tables in the database.
 |
 |      Args:
 |          query (str): The query to search for in the specified table.
 |          db (str | None): The name of the database containing the table. If None, this criterion is ignored. Default is None.
 |          table (str | None): The name of the table to search. If None, this criterion is ignored. Default is None.
 |          original_location (str | None): A string to search for in the original location of the databases. If None, this criterion is ignored. Default is None.
 |
 |  f_search_for_databases(self, db: str | None = None, table: str | None = None, original_location: str | None = None, return_output: bool = False, display_results: bool = True) -> dict | None
 |      Searches for databases in the federated system based on specified criteria such as name and original location.
 |
 |      Args:
 |          db (str | None): A string to search for in the database names. If None, this criterion is ignored. Default is None.
 |          table (str | None): A string to search for in the table names. If None, this criterion is ignored. Default is None.
 |          original_location (str | None): A string to search for in the original location of the databases. If None, this criterion is ignored. Default is None.
 |          return_output (bool): Whether to return the output as a dictionary. Default is False.
 |          display_results (bool): Whether to display the search results. Default is False.
 |
 |  f_summary(self, db: str | None = None, table: str | None = None, original_location: str | None = None) -> None
 |      Display the summary of the contents in a specified database and a database if provided within the federated system and displays it.
 |
 |      Args:
 |          db (str | None): The name of the database containing the table. If None, this criterion is ignored. Default is None.
 |          table (str | None): The name of the table to summarize. If None, this criterion is ignored. Default is None.
 |          original_location (str | None): A string to search for in the original location of the databases. If None, this criterion is ignored. Default is None.
 |
 |      Returns:
 |          The summary of the specified table.
 |
 |  init_federated(self, dsi_databases_list: list[dict])
 |      Initializes the federated system by loading metadata about the federated databases and their tables from a specified folder.
 |        This method is called during the initialization of the DSIFederated class.
 |
 |      Args:
 |          dsi_databases_list (list[dict]): A list of dictionaries containing information about each federated database.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

## Specify the folder where data was downloaded

In [4]:
workspace_folder = "/home/pascalgrosset/projects/dsi/dsi_databases_test_merge_02"

## Instantiate the object

In [5]:
federated_dbs = DSIFederated(workspace_folder, operating_mode="notebook")

## Browse and search through the data

In [6]:
#federated_dbs.f_federate(config_file=config_file, workspace_folder=workspace_folder)

,id,original_location,original_path,name,path,num_tables,tables
0,greedy-seahorse,ch-fe.lanl.gov,/users/pascalgrosset/genesis_test/model_subset...,model_subset_1.db,/home/pascalgrosset/projects/dsi/dsi_databases...,1,[data]
1,opalescent-tarsier,local,/home/pascalgrosset/projects/dsi/examples/fede...,model_subset_2.db,/home/pascalgrosset/projects/dsi/examples/fede...,1,[data]

In [8]:
federated_dbs.f_list_databases()

,id,original_location,original_path,name,path,num_tables,tables
0,nonchalant-alligator,local,/home/pascalgrosset/projects/dsi/examples/fede...,ocean_11_datasets.db,/home/pascalgrosset/projects/dsi/examples/fede...,1,[genesis_datacard]
1,accelerated-tench,url,https://www.timestored.com/data/sample/sakila.db,sakila.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,16,"[actor, country, city, address, language, cate..."
2,authentic-markhor,github,https://github.com/lanl/dsi/tree/ai_dev/tools/...,ocean_11_datasets.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,1,[genesis_datacard]
3,intelligent-roadrunner,darwin-fe.lanl.gov,/vast/projects/exasky/pascal/genesis_model_car...,modelcard.db,/home/pascalgrosset/projects/dsi/pascal_data_0...,1,[models]

In [7]:
federated_dbs.f_search_for_databases(original_location="local")

,id,original_location,original_path,name,path,num_tables,tables
1,opalescent-tarsier,local,/home/pascalgrosset/projects/dsi/examples/fede...,model_subset_2.db,/home/pascalgrosset/projects/dsi/examples/fede...,1,[data]

In [8]:
federated_dbs.f_search_for_databases(table="data")

,id,original_location,original_path,name,path,num_tables,tables
0,greedy-seahorse,ch-fe.lanl.gov,/users/pascalgrosset/genesis_test/model_subset...,model_subset_1.db,/home/pascalgrosset/projects/dsi/dsi_databases...,1,[data]
1,opalescent-tarsier,local,/home/pascalgrosset/projects/dsi/examples/fede...,model_subset_2.db,/home/pascalgrosset/projects/dsi/examples/fede...,1,[data]

In [ ]:
federated_dbs.f_search_for_databases(table="models")

## Looking up data

In [9]:
federated_dbs.f_summary()

Database: model_subset_1.db at path /home/pascalgrosset/projects/dsi/dsi_databases_test_merge_02/787f3f77ab75e2d9/model_subset_1.db:

[                                    column     type unique   min   max   avg  \
 0                               Model_Name  VARCHAR     19  None  None  None
 1                                 language  VARCHAR      2  None  None  None
 2                           master_project  VARCHAR      6  None  None  None
 3                             project_team  VARCHAR     15  None  None  None
 4                                     type  VARCHAR      4  None  None  None
 5                                  science  VARCHAR     14  None  None  None
 6                                     risk  VARCHAR      2  None  None  None
 7                                  license  VARCHAR      8  None  None  None
 8                             license_name  VARCHAR      2  None  None  None
 9                             license_link  VARCHAR      3  None  None  None
 10                              base_model  VARCHAR      8  None  None  None
 11                             new_version  INTEGER      0  None  None  None
 12                                datasets  VARCHAR     17  None  None  None
 13                                 metrics  VARCHAR     18  None  None  None
 14                            Developed by  VARCHAR     18  None  None  None
 15                          Contributed by  VARCHAR     15  None  None  None
 16                         Model Changelog  VARCHAR     18  None  None  None
 17                 Model short description  VARCHAR     17  None  None  None
 18                       Model description  VARCHAR     36  None  None  None
 19         Finetuned from model (optional)  VARCHAR      9  None  None  None
 20                              Model Type  VARCHAR     17  None  None  None
 21                      Inputs and outputs  VARCHAR     29  None  None  None
 22                  Compute Infrastructure  VARCHAR     15  None  None  None
 23                                Hardware  VARCHAR     17  None  None  None
 24                                Software  VARCHAR     16  None  None  None
 25           Papers and Scientific Outputs  VARCHAR     15  None  None  None
 26                           Model License  VARCHAR     14  None  None  None
 27     Contact Info and Model Card Authors  VARCHAR     17  None  None  None
 28                           Intended Uses  VARCHAR      9  None  None  None
 29                            Intended Use  VARCHAR     17  None  None  None
 30                  Primary Intended Users  VARCHAR     16  None  None  None
 31                       Mission Relevance  VARCHAR     16  None  None  None
 32                  Out_of_Scope Use Cases  VARCHAR     11  None  None  None
 33                              How to use  VARCHAR      8  None  None  None
 34                    Install Instructions  VARCHAR     11  None  None  None
 35                  Training configuration  VARCHAR      8  None  None  None
 36                 Inference configuration  VARCHAR      8  None  None  None
 37   Code snippets of how to use the model  VARCHAR     26  None  None  None
 38                             Limitations  VARCHAR     15  None  None  None
 39                                   Risks  VARCHAR     10  None  None  None
 40                        Training details  VARCHAR      8  None  None  None
 41                           Training data  VARCHAR     30  None  None  None
 42                      Training Procedure  VARCHAR     21  None  None  None
 43  Reproducibility Information (optional)  VARCHAR      7  None  None  None
 44                Pre_training information  VARCHAR      7  None  None  None
 45                      Evaluation details  VARCHAR      6  None  None  None
 46                         Evaluation data  VARCHAR     29  None  None  None
 47                    Evaluation Procedure  VARCHAR     22  None  None  None
 48             Uncertainty Quantification.  VARCHAR      4  None  None  None
 49                      Evaluation results  VARCHAR     28  None  None  None
 50             More Information (optional)  VARCHAR     10  None  None  None

    std_dev
 0     None
 1     None
 2     None
 3     None
 4     None
 5     None
 6     None
 7     None
 8     None
 9     None
 10    None
 11    None
 12    None
 13    None
 14    None
 15    None
 16    None
 17    None
 18    None
 19    None
 20    None
 21    None
 22    None
 23    None
 24    None
 25    None
 26    None
 27    None
 28    None
 29    None
 30    None
 31    None
 32    None
 33    None
 34    None
 35    None
 36    None
 37    None
 38    None
 39    None
 40    None
 41    None
 42    None
 43    None
 44    None
 45    None
 46    None
 47    None
 48    None
 49    None
 50    None  ]

Database: model_subset_2.db  at path /home/pascalgrosset/projects/dsi/examples/federated/tests/model_subset_2.db:

[                                    column     type unique   min   max   avg  \
 0                               Model_Name  VARCHAR      2  None  None  None
 1                                 language  VARCHAR      1  None  None  None
 2                           master_project  VARCHAR      3  None  None  None
 3                             project_team  VARCHAR      3  None  None  None
 4                                     type  VARCHAR      3  None  None  None
 5                                  science  VARCHAR      3  None  None  None
 6                                     risk  VARCHAR      1  None  None  None
 7                                  license  VARCHAR      2  None  None  None
 8                             license_name  VARCHAR      1  None  None  None
 9                             license_link  VARCHAR      1  None  None  None
 10                              base_model  VARCHAR      3  None  None  None
 11                             new_version  INTEGER      0  None  None  None
 12                                datasets  VARCHAR      1  None  None  None
 13                                 metrics  VARCHAR      3  None  None  None
 14                            Developed by  VARCHAR      3  None  None  None
 15                          Contributed by  VARCHAR      3  None  None  None
 16                         Model Changelog  VARCHAR      2  None  None  None
 17                 Model short description  VARCHAR      2  None  None  None
 18                       Model description  VARCHAR     30  None  None  None
 19         Finetuned from model (optional)  VARCHAR      1  None  None  None
 20                              Model Type  VARCHAR      1  None  None  None
 21                      Inputs and outputs  VARCHAR     25  None  None  None
 22                  Compute Infrastructure  VARCHAR      1  None  None  None
 23                                Hardware  VARCHAR      6  None  None  None
 24                                Software  VARCHAR      2  None  None  None
 25           Papers and Scientific Outputs  VARCHAR      2  None  None  None
 26                           Model License  VARCHAR      2  None  None  None
 27     Contact Info and Model Card Authors  VARCHAR      3  None  None  None
 28                           Intended Uses  VARCHAR      3  None  None  None
 29                            Intended Use  VARCHAR      1  None  None  None
 30                  Primary Intended Users  VARCHAR      3  None  None  None
 31                       Mission Relevance  VARCHAR      2  None  None  None
 32                  Out_of_Scope Use Cases  VARCHAR      2  None  None  None
 33                              How to use  VARCHAR      2  None  None  None
 34                    Install Instructions  VARCHAR      3  None  None  None
 35                  Training configuration  VARCHAR      1  None  None  None
 36                 Inference configuration  VARCHAR      2  None  None  None
 37   Code snippets of how to use the model  VARCHAR     28  None  None  None
 38                             Limitations  VARCHAR      2  None  None  None
 39                                   Risks  VARCHAR      3  None  None  None
 40                        Training details  VARCHAR      1  None  None  None
 41                           Training data  VARCHAR     27  None  None  None
 42                      Training Procedure  VARCHAR     15  None  None  None
 43  Reproducibility Information (optional)  VARCHAR      1  None  None  None
 44                Pre_training information  VARCHAR      9  None  None  None
 45                      Evaluation details  VARCHAR      2  None  None  None
 46                         Evaluation data  VARCHAR     26  None  None  None
 47                    Evaluation Procedure  VARCHAR     16  None  None  None
 48             Uncertainty Quantification.  VARCHAR      1  None  None  None
 49                      Evaluation results  VARCHAR     25  None  None  None
 50             More Information (optional)  VARCHAR      1  None  None  None

    std_dev
 0     None
 1     None
 2     None
 3     None
 4     None
 5     None
 6     None
 7     None
 8     None
 9     None
 10    None
 11    None
 12    None
 13    None
 14    None
 15    None
 16    None
 17    None
 18    None
 19    None
 20    None
 21    None
 22    None
 23    None
 24    None
 25    None
 26    None
 27    None
 28    None
 29    None
 30    None
 31    None
 32    None
 33    None
 34    None
 35    None
 36    None
 37    None
 38    None
 39    None
 40    None
 41    None
 42    None
 43    None
 44    None
 45    None
 46    None
 47    None
 48    None
 49    None
 50    None  ]

federated_dbs.f_search(query="dens_max")

In [ ]:
federated_dbs.f_summary()

In [10]:
federated_dbs.f_search(query="dens_max")

WARNING: 'dens_max' was not found in this backend

WARNING: 'dens_max' was not found in this backend

[None, None]

## Merging data

### Search for databases

In [ ]:
federated_dbs.f_search_for_databases(db="data_subset*")

### Search for the path to a database

In [ ]:
federated_dbs.f_get_db_path(db="data_subset_1.db")

### Load that database

In [ ]:
temp_file = DSI('/Users/pascalgrosset/projects/dsi/dsi_databases_00/87c1361f3c2316dd/data_subset_1.db')

In [ ]:
temp_file.list()

In [ ]:
temp_file.get_table("data", collection=True)

In [ ]:
federated_dbs.f_merge(src_db_id='camouflaged-hare',src_tbl_name='data', dst_db_id='aromatic-dragon',dst_tbl_name='data')

In [ ]:
temp_file.get_table("data", collection=True)

In [ ]:
federated_dbs.f_merge(src_db_id='precious-walrus',src_tbl_name='data', dst_db_id='aromatic-dragon',dst_tbl_name='data')

In [ ]:
temp_file.get_table("data", collection=True)

## Adding another table to the database

In [ ]:
federated_dbs.f_search_for_databases(db="model_subset*")

In [ ]:
federated_dbs.f_add_table(src_db_id='satisfied-whale',src_tbl_name='data', dst_db_id='aromatic-dragon',dst_tbl_name='model')

In [ ]:
temp_file.list()

In [ ]:
temp_file.get_table("model", collection=True)

That database now has datasets which have been pulled from different sites as well as several tables